/*
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
*/
(function(){function b(f){f=String(f);return f.charAt(0).toUpperCase()+f.slice(1)}function n(f,w){var y=-1,z=f?f.length:0;if("number"==typeof z&&-1<z&&z<=v)for(;++y<z;)w(f[y],y,f);else a(f,w)}function e(f){f=String(f).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(f)?f:b(f)}function a(f,w){for(var y in f)r.call(f,y)&&w(f[y],y,f)}function c(f){return null==f?b(f):x.call(f).slice(8,-1)}function q(f,w){var y=null!=f?typeof f[w]:"number";return!/^(?:boolean|number|string|undefined)$/.test(y)&&
("object"==y?!!f[w]:!0)}function d(f){return String(f).replace(/([ -])(?!$)/g,"$1?")}function p(f,w){var y=null;n(f,function(z,E){y=w(y,z,E,f)});return y}function h(f){function w(J){return p(J,function(I,H){var K=H.pattern||d(H);!I&&(I=RegExp("\\b"+K+" *\\d+[.\\w_]*","i").exec(f)||RegExp("\\b"+K+" *\\w+-[\\w]*","i").exec(f)||RegExp("\\b"+K+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(f))&&((I=String(H.label&&!RegExp(K,"i").test(H.label)?H.label:I).split("/"))[1]&&!/[\d.]+/.test(I[0])&&(I[0]+=
" "+I[1]),H=H.label||H,I=e(I[0].replace(RegExp(K,"i"),H).replace(RegExp("; *(?:"+H+"[_-])?","i")," ").replace(RegExp("("+H+")[-_.]?(\\w)","i"),"$1 $2")));return I})}function y(J){return p(J,function(I,H){return I||(RegExp(H+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(f)||0)[1]||null})}var z=m,E=f&&"object"==typeof f&&"String"!=c(f);E&&(z=f,f=null);var M=z.navigator||{},D=M.userAgent||"";f||(f=D);var Z=E?!!M.likeChrome:/\bChrome\b/.test(f)&&!/internal|\n/i.test(x.toString()),
aa=E?"Object":"ScriptBridgingProxyObject",U=E?"Object":"Environment",Q=E&&z.java?"JavaPackage":c(z.java),ba=E?"Object":"RuntimeObject";U=(Q=/\bJava/.test(Q)&&z.java)&&c(z.environment)==U;var ca=Q?"a":"\u03b1",da=Q?"b":"\u03b2",V=z.document||{},O=z.operamini||z.opera,R=u.test(R=E&&O?O["[[Class]]"]:c(O))?R:O=null,t,S=f;E=[];var T=null,P=f==D;D=P&&O&&"function"==typeof O.version&&O.version();var F=function(J){return p(J,function(I,H){return I||RegExp("\\b"+(H.pattern||d(H))+"\\b","i").exec(f)&&(H.label||
H)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),A=function(J){return p(J,function(I,H){return I||RegExp("\\b"+(H.pattern||d(H))+"\\b","i").exec(f)&&(H.label||H)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori","Nook Browser",
"PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},
{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),G=w([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad",
"iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),L=function(J){return p(J,function(I,H,K){return I||(H[G]||H[/^[a-z]+(?: +[a-z]+\b)*/i.exec(G)]||RegExp("\\b"+d(K)+"(?:\\b|\\w*\\d)","i").exec(f))&&K})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},
"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),B=function(J){return p(J,function(I,H){var K=H.pattern||d(H);if(!I&&(I=RegExp("\\b"+K+"(?:/[\\d.]+|[ \\w.]*)","i").exec(f))){var N=I,W=H.label||H,X={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};K&&W&&/^Win/i.test(N)&&!/^Windows Phone /i.test(N)&&(X=X[/[\d.]+$/.exec(N)])&&(N="Windows "+X);N=String(N);K&&W&&(N=N.replace(RegExp(K,"i"),W));I=N=e(N.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,"$1").replace(/\/(\d)/,
" $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return I})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X","Macintosh","Mac",
"Windows 98;","Windows "]);F&&(F=[F]);L&&!G&&(G=w([L]));if(t=/\bGoogle TV\b/.exec(G))G=t[0];/\bSimulator\b/i.test(f)&&(G=(G?G+" ":"")+"Simulator");"Opera Mini"==A&&/\bOPiOS\b/.test(f)&&E.push("running in Turbo/Uncompressed mode");"IE"==A&&/\blike iPhone OS\b/.test(f)?(t=h(f.replace(/like iPhone OS/,"")),L=t.manufacturer,G=t.product):/^iP/.test(G)?(A||(A="Safari"),B="iOS"+((t=/ OS ([\d_]+)/i.exec(f))?" "+t[1].replace(/_/g,"."):"")):"Konqueror"!=A||/buntu/i.test(B)?L&&"Google"!=L&&(/Chrome/.test(A)&&
!/\bMobile Safari\b/i.test(f)||/\bVita\b/.test(G))||/\bAndroid\b/.test(B)&&/^Chrome/.test(A)&&/\bVersion\//i.test(f)?(A="Android Browser",B=/\bAndroid\b/.test(B)?B:"Android"):"Silk"==A?(/\bMobi/i.test(f)||(B="Android",E.unshift("desktop mode")),/Accelerated *= *true/i.test(f)&&E.unshift("accelerated")):"PaleMoon"==A&&(t=/\bFirefox\/([\d.]+)\b/.exec(f))?E.push("identifying as Firefox "+t[1]):"Firefox"==A&&(t=/\b(Mobile|Tablet|TV)\b/i.exec(f))?(B||(B="Firefox OS"),G||(G=t[1])):!A||(t=!/\bMinefield\b/i.test(f)&&
/\b(?:Firefox|Safari)\b/.exec(A))?(A&&!G&&/[\/,]|^[^(]+?\)/.test(f.slice(f.indexOf(t+"/")+8))&&(A=null),(t=G||L||B)&&(G||L||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(B))&&(A=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(B)?B:t)+" Browser")):"Electron"==A&&(t=(/\bChrome\/([\d.]+)\b/.exec(f)||0)[1])&&E.push("Chromium "+t):B="Kubuntu";D||(D=y(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",d(A),"(?:Firefox|Minefield|NetFront)"]));
if(t="iCab"==F&&3<parseFloat(D)&&"WebKit"||/\bOpera\b/.test(A)&&(/\bOPR\b/.test(f)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(f)&&!/^(?:Trident|EdgeHTML)$/.test(F)&&"WebKit"||!F&&/\bMSIE\b/i.test(f)&&("Mac OS"==B?"Tasman":"Trident")||"WebKit"==F&&/\bPlayStation\b(?! Vita\b)/i.test(A)&&"NetFront")F=[t];"IE"==A&&(t=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(f)||0)[1])?(A+=" Mobile",B="Windows Phone "+(/\+$/.test(t)?t:t+".x"),E.unshift("desktop mode")):/\bWPDesktop\b/i.test(f)?(A="IE Mobile",B="Windows Phone 8.x",
E.unshift("desktop mode"),D||(D=(/\brv:([\d.]+)/.exec(f)||0)[1])):"IE"!=A&&"Trident"==F&&(t=/\brv:([\d.]+)/.exec(f))&&(A&&E.push("identifying as "+A+(D?" "+D:"")),A="IE",D=t[1]);if(P){if(q(z,"global"))if(Q&&(t=Q.lang.System,S=t.getProperty("os.arch"),B=B||t.getProperty("os.name")+" "+t.getProperty("os.version")),U){try{D=z.require("ringo/engine").version.join("."),A="RingoJS"}catch(J){(t=z.system)&&t.global.system==z.system&&(A="Narwhal",B||(B=t[0].os||null))}A||(A="Rhino")}else"object"==typeof z.process&&
!z.process.browser&&(t=z.process)&&("object"==typeof t.versions&&("string"==typeof t.versions.electron?(E.push("Node "+t.versions.node),A="Electron",D=t.versions.electron):"string"==typeof t.versions.nw&&(E.push("Chromium "+D,"Node "+t.versions.node),A="NW.js",D=t.versions.nw)),A||(A="Node.js",S=t.arch,B=t.platform,D=(D=/[\d.]+/.exec(t.version))?D[0]:null));else c(t=z.runtime)==aa?(A="Adobe AIR",B=t.flash.system.Capabilities.os):c(t=z.phantom)==ba?(A="PhantomJS",D=(t=t.version||null)&&t.major+"."+
t.minor+"."+t.patch):"number"==typeof V.documentMode&&(t=/\bTrident\/(\d+)/i.exec(f))?(D=[D,V.documentMode],(t=+t[1]+4)!=D[1]&&(E.push("IE "+D[1]+" mode"),F&&(F[1]=""),D[1]=t),D="IE"==A?String(D[1].toFixed(1)):D[0]):"number"==typeof V.documentMode&&/^(?:Chrome|Firefox)\b/.test(A)&&(E.push("masking as "+A+" "+D),A="IE",D="11.0",F=["Trident"],B="Windows");B=B&&e(B)}D&&(t=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(D)||/(?:alpha|beta)(?: ?\d)?/i.exec(f+";"+(P&&M.appMinorVersion))||/\bMinefield\b/i.test(f)&&
"a")&&(T=/b/i.test(t)?"beta":"alpha",D=D.replace(RegExp(t+"\\+?$"),"")+("beta"==T?da:ca)+(/\d+\+?/.exec(t)||""));if("Fennec"==A||"Firefox"==A&&/\b(?:Android|Firefox OS)\b/.test(B))A="Firefox Mobile";else if("Maxthon"==A&&D)D=D.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(G))"Xbox 360"==G&&(B=null),"Xbox 360"==G&&/\bIEMobile\b/.test(f)&&E.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(A)&&(!A||G||/Browser|Mobi/.test(A))||"Windows CE"!=B&&!/Mobi/i.test(f))if("IE"==A&&P)try{null===
z.external&&E.unshift("platform preview")}catch(J){E.unshift("embedded")}else(/\bBlackBerry\b/.test(G)||/\bBB10\b/.test(f))&&(t=(RegExp(G.replace(/ +/g," *")+"/([.\\d]+)","i").exec(f)||0)[1]||D)?(t=[t,/BB10/.test(f)],B=(t[1]?(G=null,L="BlackBerry"):"Device Software")+" "+t[0],D=null):this!=a&&"Wii"!=G&&(P&&O||/Opera/.test(A)&&/\b(?:MSIE|Firefox)\b/i.test(f)||"Firefox"==A&&/\bOS X (?:\d+\.){2,}/.test(B)||"IE"==A&&(B&&!/^Win/.test(B)&&5.5<D||/\bWindows XP\b/.test(B)&&8<D||8==D&&!/\bTrident\b/.test(f)))&&
!u.test(t=h.call(a,f.replace(u,"")+";"))&&t.name&&(t="ing as "+t.name+((t=t.version)?" "+t:""),u.test(A)?(/\bIE\b/.test(t)&&"Mac OS"==B&&(B=null),t="identify"+t):(t="mask"+t,A=R?e(R.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(t)&&(B=null),P||(D=null)),F=["Presto"],E.push(t));else A+=" Mobile";if(t=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(f)||0)[1]){t=[parseFloat(t.replace(/\.(\d)$/,".0$1")),t];if("Safari"==A&&"+"==t[1].slice(-1))A="WebKit Nightly",T="alpha",D=t[1].slice(0,-1);else if(D==
t[1]||D==(t[2]=(/\bSafari\/([\d.]+\+?)/i.exec(f)||0)[1]))D=null;t[1]=(/\bChrome\/([\d.]+)/i.exec(f)||0)[1];537.36==t[0]&&537.36==t[2]&&28<=parseFloat(t[1])&&"WebKit"==F&&(F=["Blink"]);P&&(Z||t[1])?(F&&(F[1]="like Chrome"),t=t[1]||(t=t[0],530>t?1:532>t?2:532.05>t?3:533>t?4:534.03>t?5:534.07>t?6:534.1>t?7:534.13>t?8:534.16>t?9:534.24>t?10:534.3>t?11:535.01>t?12:535.02>t?"13+":535.07>t?15:535.11>t?16:535.19>t?17:536.05>t?18:536.1>t?19:537.01>t?20:537.11>t?"21+":537.13>t?23:537.18>t?24:537.24>t?25:537.36>
t?26:"Blink"!=F?"27":"28")):(F&&(F[1]="like Safari"),t=(t=t[0],400>t?1:500>t?2:526>t?3:533>t?4:534>t?"4+":535>t?5:537>t?6:538>t?7:601>t?8:"8"));F&&(F[1]+=" "+(t+="number"==typeof t?".x":/[.+]/.test(t)?"":"+"));"Safari"==A&&(!D||45<parseInt(D))&&(D=t)}"Opera"==A&&(t=/\bzbov|zvav$/.exec(B))?(A+=" ",E.unshift("desktop mode"),"zvav"==t?(A+="Mini",D=null):A+="Mobile",B=B.replace(RegExp(" *"+t+"$"),"")):"Safari"==A&&/\bChrome\b/.exec(F&&F[1])&&(E.unshift("desktop mode"),A="Chrome Mobile",D=null,/\bOS X\b/.test(B)?
(L="Apple",B="iOS 4.3+"):B=null);D&&0==D.indexOf(t=/[\d.]+$/.exec(B))&&-1<f.indexOf("/"+t+"-")&&(B=String(B.replace(t,"")).replace(/^ +| +$/g,""));F&&!/\b(?:Avant|Nook)\b/.test(A)&&(/Browser|Lunascape|Maxthon/.test(A)||"Safari"!=A&&/^iOS/.test(B)&&/\bSafari\b/.test(F[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(A)&&F[1])&&(t=F[F.length-1])&&E.push(t);E.length&&(E=["("+E.join("; ")+")"]);L&&G&&0>G.indexOf(L)&&E.push("on "+L);G&&E.push((/^on /.test(E[E.length-
1])?"":"on ")+G);if(B){var Y=(t=/ ([\d.+]+)$/.exec(B))&&"/"==B.charAt(B.length-t[0].length-1);B={architecture:32,family:t&&!Y?B.replace(t[0],""):B,version:t?t[1]:null,toString:function(){var J=this.version;return this.family+(J&&!Y?" "+J:"")+(64==this.architecture?" 64-bit":"")}}}(t=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(S))&&!/\bi686\b/i.test(S)?(B&&(B.architecture=64,B.family=B.family.replace(RegExp(" *"+t),"")),A&&(/\bWOW64\b/i.test(f)||P&&/\w(?:86|32)$/.test(M.cpuClass||M.platform)&&!/\bWin64; x64\b/i.test(f))&&
E.unshift("32-bit")):B&&/^OS X/.test(B.family)&&"Chrome"==A&&39<=parseFloat(D)&&(B.architecture=64);f||(f=null);z={};z.description=f;z.layout=F&&F[0];z.manufacturer=L;z.name=A;z.prerelease=T;z.product=G;z.ua=f;z.version=A&&D;z.os=B||{architecture:null,family:null,version:null,toString:function(){return"null"}};z.parse=h;z.toString=function(){return this.description||""};z.version&&E.unshift(D);z.name&&E.unshift(A);B&&A&&(B!=String(B).split(" ")[0]||B!=A.split(" ")[0]&&!G)&&E.push(G?"("+B+")":"on "+
B);E.length&&(z.description=E.join(" "));return z}var g={"function":!0,object:!0},m=g[typeof window]&&window||this,l=g[typeof exports]&&exports;g=g[typeof module]&&module&&!module.nodeType&&module;var k=l&&g&&"object"==typeof global&&global;!k||k.global!==k&&k.window!==k&&k.self!==k||(m=k);var v=Math.pow(2,53)-1,u=/\bOpera/;k=Object.prototype;var r=k.hasOwnProperty,x=k.toString,C=h();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(m.platform=C,define(function(){return C})):l&&
g?a(C,function(f,w){l[w]=f}):m.platform=C}).call(this);
function buildIOSMeta(){for(var b=[{name:"viewport",content:"width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"},{name:"apple-mobile-web-app-capable",content:"yes"},{name:"apple-mobile-web-app-status-bar-style",content:"black"}],n=0;n<b.length;n++){var e=document.createElement("meta");e.name=b[n].name;e.content=b[n].content;var a=window.document.head.querySelector('meta[name="'+e.name+'"]');a&&a.parentNode.removeChild(a);window.document.head.appendChild(e)}}
function hideIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","none");jQuery(".xxx-ios-fullscreen-scroll").css("display","none");jQuery(".xxx-game-iframe-full").removeClass("xxx-game-iframe-iphone-se")}function buildIOSFullscreenPanel(){jQuery("body").append('<div class="xxx-ios-fullscreen-message"><div class="xxx-ios-fullscreen-swipe"></div></div><div class="xxx-ios-fullscreen-scroll"></div>')}
function showIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","block");jQuery(".xxx-ios-fullscreen-scroll").css("display","block")}
function __iosResize(){window.scrollTo(0,0);console.log(window.devicePixelRatio);console.log(window.innerWidth);console.log(window.innerHeight);if("iPhone"===platform.product)switch(window.devicePixelRatio){case 2:switch(window.innerWidth){case 568:320!==window.innerHeight&&jQuery(".xxx-game-iframe-full").addClass("xxx-game-iframe-iphone-se");break;case 667:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();
break;default:hideIOSFullscreenPanel()}break;case 3:switch(window.innerWidth){case 736:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 724:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;default:hideIOSFullscreenPanel()}}function iosResize(){__iosResize();setTimeout(function(){__iosResize()},500)}
function iosInIframe(){try{return window.self!==window.top}catch(b){return!0}}function isIOSLessThen13(){var b=platform.os,n=b.family.toLowerCase();b=parseFloat(b.version);return"ios"===n&&13>b?!0:!1}$(document).ready(function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&(buildIOSFullscreenPanel(),buildIOSMeta())});
jQuery(window).resize(function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&iosResize()});var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop,s_bIsIphone=!1,s_bFocus=!0;
(function(b){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(b)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(b.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(b){console.log(b)}function isIOS(){var b="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");if(-1!==navigator.userAgent.toLowerCase().indexOf("iphone"))return s_bIsIphone=!0;for(;b.length;)if(navigator.platform===b.pop())return!0;return s_bIsIphone=!1}
function isIpad(){var b=-1!==navigator.userAgent.toLowerCase().indexOf("ipad");return!b&&navigator.userAgent.match(/Mac/)&&navigator.maxTouchPoints&&2<navigator.maxTouchPoints?!0:b}function isMobile(){return isIpad()?!0:jQuery.browser.mobile}
function getSize(b){var n=b.toLowerCase(),e=window.document,a=e.documentElement;if(void 0===window["inner"+b])b=a["client"+b];else if(window["inner"+b]!=a["client"+b]){var c=e.createElement("body");c.id="vpw-test-b";c.style.cssText="overflow:scroll";var q=e.createElement("div");q.id="vpw-test-d";q.style.cssText="position:absolute;top:-1000px";q.innerHTML="<style>@media("+n+":"+a["client"+b]+"px){body#vpw-test-b div#vpw-test-d{"+n+":7px!important}}</style>";c.appendChild(q);a.insertBefore(c,e.head);
b=7==q["offset"+b]?a["client"+b]:window["inner"+b];a.removeChild(c)}else b=window["inner"+b];return b}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var b=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<b?b:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var b=null!==platform.name&&"safari"===platform.name.toLowerCase()?getIOSWindowHeight():getSize("Height");var n=getSize("Width");s_bFocus&&_checkOrientation(n,b);var e=Math.min(b/CANVAS_HEIGHT,n/CANVAS_WIDTH),a=Math.round(CANVAS_WIDTH*e);e=Math.round(CANVAS_HEIGHT*e);if(e<b){var c=b-e;e+=c;a+=CANVAS_WIDTH/CANVAS_HEIGHT*c}else a<n&&(c=n-a,a+=c,e+=CANVAS_HEIGHT/CANVAS_WIDTH*c);c=b/2-e/2;var q=n/2-a/2,d=CANVAS_WIDTH/a;if(q*d<-EDGEBOARD_X||
c*d<-EDGEBOARD_Y)e=Math.min(b/(CANVAS_HEIGHT-2*EDGEBOARD_Y),n/(CANVAS_WIDTH-2*EDGEBOARD_X)),a=Math.round(CANVAS_WIDTH*e),e=Math.round(CANVAS_HEIGHT*e),c=(b-e)/2,q=(n-a)/2,d=CANVAS_WIDTH/a;s_iOffsetX=-1*q*d;s_iOffsetY=-1*c*d;0<=c&&(s_iOffsetY=0);0<=q&&(s_iOffsetX=0);null!==s_oGame&&s_oGame.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oBetPanel&&s_oBetPanel.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsIphone?(canvas=document.getElementById("canvas"),
s_oStage.canvas.width=2*a,s_oStage.canvas.height=2*e,canvas.style.width=a+"px",canvas.style.height=e+"px",n=Math.min(a/CANVAS_WIDTH,e/CANVAS_HEIGHT),s_iScaleFactor=2*n,s_oStage.scaleX=s_oStage.scaleY=2*n):s_bMobile&&!1===isIOS()?($("#canvas").css("width",a+"px"),$("#canvas").css("height",e+"px")):(s_oStage.canvas.width=a,s_oStage.canvas.height=e,s_iScaleFactor=Math.min(a/CANVAS_WIDTH,e/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>c||(c=(b-e)/2);$("#canvas").css("top",c+"px");$("#canvas").css("left",
q+"px");fullscreenHandler()}}
function _checkOrientation(b,n){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(b>n?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(b){return!0}}function createBitmap(b,n,e){var a=new createjs.Bitmap(b),c=new createjs.Shape;n&&e?c.graphics.beginFill("#fff").drawRect(0,0,n,e):c.graphics.beginFill("#ff0").drawRect(0,0,b.width,b.height);a.hitArea=c;return a}function createSprite(b,n,e,a,c,q){b=null!==n?new createjs.Sprite(b,n):new createjs.Sprite(b);n=new createjs.Shape;n.graphics.beginFill("#000000").drawRect(-e,-a,c,q);b.hitArea=n;return b}
function randomFloatBetween(b,n,e){"undefined"===typeof e&&(e=2);return parseFloat(Math.min(b+Math.random()*(n-b),n).toFixed(e))}function formatTime(b){b/=1E3;var n=Math.floor(b/60);b=Math.floor(b-60*n);var e="";e=10>n?e+("0"+n+":"):e+(n+":");return 10>b?e+("0"+b):e+b}function NoClickDelay(b){this.element=b;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(b){for(var n=b.length,e,a;0<n;)a=Math.floor(Math.random()*n),n--,e=b[n],b[n]=b[a],b[a]=e;return b}
NoClickDelay.prototype={handleEvent:function(b){switch(b.type){case "touchstart":this.onTouchStart(b);break;case "touchmove":this.onTouchMove(b);break;case "touchend":this.onTouchEnd(b)}},onTouchStart:function(b){b.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(b){this.moved=!0},onTouchEnd:function(b){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){b=document.elementFromPoint(b.changedTouches[0].clientX,b.changedTouches[0].clientY);3==b.nodeType&&(b=b.parentNode);var n=document.createEvent("MouseEvents");n.initEvent("click",!0,!0);b.dispatchEvent(n)}}};function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(b){for(var n=window.location.search.substring(1).split("&"),e=0;e<n.length;e++){var a=n[e].split("=");if(a[0]==b)return a[1]}}Array.prototype.sortOn=function(){var b=this.slice();if(!arguments.length)return b.sort();var n=Array.prototype.slice.call(arguments);return b.sort(function(e,a){for(var c=n.slice(),q=c.shift();e[q]==a[q]&&c.length;)q=c.shift();return e[q]==a[q]?0:e[q]>a[q]?1:-1})};
function playSound(b,n,e){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[b].play(),s_aSounds[b].volume(n),s_aSounds[b].loop(e),s_aSounds[b]):null}function stopSound(b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[b].stop()}function setVolume(b,n){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[b].volume(n)}function setMute(b,n){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[b].mute(n)}function pauseSound(b){s_aSounds[b].pause()}
function easeLinear(b,n,e,a){return e*b/a+n}function collisionWithCircle(b,n,e){var a=b.getX()-n.getX(),c=b.getY()-n.getY();return Math.sqrt(a*a+c*c)<b.getCollision()*e+n.getCollision()*e?!0:!1}
(function(){function b(e){var a={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};e=e||window.event;e.type in a?document.body.className=a[e.type]:(document.body.className=this[n]?"hidden":"visible","hidden"===document.body.className?(s_oMain.stopUpdate(),s_bFocus=!1):(s_oMain.startUpdate(),s_bFocus=!0))}var n="hidden";n in document?document.addEventListener("visibilitychange",b):(n="mozHidden")in document?document.addEventListener("mozvisibilitychange",
b):(n="webkitHidden")in document?document.addEventListener("webkitvisibilitychange",b):(n="msHidden")in document?document.addEventListener("msvisibilitychange",b):"onfocusin"in document?document.onfocusin=document.onfocusout=b:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=b})();
function fullscreenHandler(){ENABLE_FULLSCREEN&&screenfull.isEnabled&&(s_bFullscreen=screenfull.isFullscreen,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut())}if(screenfull.isEnabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut()});
function CSpriteLibrary(){var b={},n,e,a,c,q,d;this.init=function(p,h,g){n={};a=e=0;c=p;q=h;d=g};this.addSprite=function(p,h){if(b.hasOwnProperty(p))return!1;var g=new Image;b[p]=n[p]={szPath:h,oSprite:g,bLoaded:!1};e++;return!0};this.getSprite=function(p){return b.hasOwnProperty(p)?b[p].oSprite:null};this._onSpritesLoaded=function(){e=0;q.call(d)};this._onSpriteLoaded=function(){c.call(d);++a===e&&this._onSpritesLoaded()};this.loadSprites=function(){for(var p in n)n[p].oSprite.oSpriteLibrary=this,
n[p].oSprite.szKey=p,n[p].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},n[p].oSprite.onerror=function(h){var g=h.currentTarget;setTimeout(function(){n[g.szKey].oSprite.src=n[g.szKey].szPath},500)},n[p].oSprite.src=n[p].szPath};this.setLoaded=function(p){b[p].bLoaded=!0};this.isLoaded=function(p){return b[p].bLoaded};this.getNumSprites=function(){return e}}
var CANVAS_WIDTH=1024,CANVAS_HEIGHT=768,EDGEBOARD_X=0,EDGEBOARD_Y=168,FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="impactregular",SECONDARY_FONT="Digital-7",TERTIARY_FONT="InfiniteJustice",STATE_LOADING=0,STATE_MENU=1,STATE_BET_PANEL=2,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,CHIP_VALUES,BET_PANEL_X=70,BET_PANEL_Y=165,BET_PANEL_WIDTH,BET_PANEL_HEIGHT,GREYHOUND_WIDTH=338,GREYHOUND_HEIGHT=170,NUM_CHIPS,NUM_GREYHOUNDS,MIN_BET,
MAX_BET,WIN_OCCURRENCE,NUM_TRACK_BG=416,RACE_TIME=Math.round(NUM_TRACK_BG/(FPS/2)),ARRIVAL_X=491,TIME_CHECK_RANK=3E3,COLOR_FICHES="#ff7706 #ffb600 #000 #06a800 #d50000 #444444".split(" "),ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION,SHOW_CREDITS,SOUNDTRACK_VOLUME_IN_GAME=0;
function CGameSettings(b){var n,e,a,c,q,d,p,h,g;this._init=function(m){g=m;m=g.greyhound_names;NUM_GREYHOUNDS=m.length;n=[];for(var l=0;l<NUM_GREYHOUNDS;l++)n[l]=m[l];this._initSimpleOdd();this._initForecastOdd();this._initPaths();this._initGreyhoundInfo();d=CHIP_VALUES};this._initSimpleOdd=function(){var m=g.odd_win_bet,l=g.odd_place_bet,k=g.odd_show_bet;e=[];a=[];c=[];for(var v=0;v<m.length;v++)e[v]=m[v],a[v]=l[v],c[v]=k[v]};this._initForecastOdd=function(){var m=g.forecast;q=[];for(var l=0;l<NUM_GREYHOUNDS;l++)q[l]=
[];for(l=0;l<m.length;l++)q[m[l].first-1][m[l].second-1]=m[l].odd};this._initPaths=function(){p=[];var m=[{x:230,frame:30},{x:500,frame:180},{x:600,frame:180},{x:400,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}],l=[{x:250,frame:30},{x:600,frame:200},{x:650,frame:180},{x:450,frame:180},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:35}],k=[{x:170,frame:30},{x:400,frame:150},{x:450,frame:210},{x:400,frame:140},{x:300,
frame:130},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:40}],v=[{x:190,frame:30},{x:340,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:45}],u=[{x:220,frame:30},{x:350,frame:280},{x:480,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-450,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:50}],r=[{x:210,frame:30},{x:260,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-600,frame:480},{x:CANVAS_WIDTH+
GREYHOUND_WIDTH,frame:55}];p.push({place_1:m,place_2:l,place_3:k,place_4:v,place_5:u,place_6:r});m=[{x:230,frame:30},{x:450,frame:180},{x:500,frame:180},{x:400,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];l=[{x:250,frame:30},{x:600,frame:200},{x:550,frame:180},{x:350,frame:180},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:35}];k=[{x:170,frame:30},{x:450,frame:150},{x:550,frame:210},{x:500,frame:140},{x:400,frame:130},
{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:40}];v=[{x:190,frame:30},{x:300,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:45}];u=[{x:220,frame:30},{x:350,frame:280},{x:400,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-450,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:50}];r=[{x:210,frame:30},{x:360,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-600,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,
frame:55}];p.push({place_1:m,place_2:l,place_3:k,place_4:v,place_5:u,place_6:r});m=[{x:230,frame:30},{x:500,frame:180},{x:600,frame:180},{x:600,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];l=[{x:250,frame:30},{x:600,frame:200},{x:650,frame:180},{x:500,frame:180},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:35}];k=[{x:170,frame:30},{x:400,frame:150},{x:450,frame:210},{x:600,frame:140},{x:450,frame:130},{x:ARRIVAL_X-
GREYHOUND_WIDTH/2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:40}];v=[{x:190,frame:30},{x:340,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-410,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:45}];u=[{x:220,frame:30},{x:350,frame:280},{x:480,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:50}];r=[{x:210,frame:30},{x:260,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:55}];
p.push({place_1:m,place_2:l,place_3:k,place_4:v,place_5:u,place_6:r});m=[{x:330,frame:30},{x:450,frame:180},{x:550,frame:180},{x:650,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];l=[{x:250,frame:30},{x:350,frame:200},{x:450,frame:180},{x:600,frame:180},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:35}];k=[{x:270,frame:30},{x:400,frame:150},{x:450,frame:210},{x:600,frame:140},{x:500,frame:130},{x:ARRIVAL_X-GREYHOUND_WIDTH/
2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:40}];v=[{x:290,frame:30},{x:340,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-410,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:45}];u=[{x:220,frame:30},{x:350,frame:280},{x:400,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:50}];r=[{x:210,frame:30},{x:360,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:55}];p.push({place_1:m,
place_2:l,place_3:k,place_4:v,place_5:u,place_6:r});m=[{x:230,frame:30},{x:350,frame:180},{x:400,frame:180},{x:600,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];l=[{x:250,frame:30},{x:350,frame:200},{x:450,frame:180},{x:500,frame:180},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:35}];k=[{x:270,frame:30},{x:400,frame:150},{x:450,frame:210},{x:600,frame:140},{x:500,frame:130},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,
frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:40}];v=[{x:190,frame:30},{x:340,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:45}];u=[{x:220,frame:30},{x:350,frame:280},{x:400,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:50}];r=[{x:210,frame:30},{x:260,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:55}];p.push({place_1:m,
place_2:l,place_3:k,place_4:v,place_5:u,place_6:r});m=[{x:230,frame:50},{x:350,frame:200},{x:400,frame:100},{x:500,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:250},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];l=[{x:250,frame:100},{x:350,frame:150},{x:450,frame:150},{x:500,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:35}];k=[{x:270,frame:50},{x:400,frame:150},{x:450,frame:200},{x:400,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:200},{x:CANVAS_WIDTH+
GREYHOUND_WIDTH,frame:40}];v=[{x:190,frame:30},{x:340,frame:170},{x:360,frame:300},{x:380,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:45}];u=[{x:220,frame:100},{x:350,frame:200},{x:400,frame:200},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:50}];r=[{x:210,frame:50},{x:260,frame:300},{x:300,frame:200},{x:220,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:150},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,
frame:55}];p.push({place_1:m,place_2:l,place_3:k,place_4:v,place_5:u,place_6:r});m=[{x:230,frame:50},{x:430,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];l=[{x:250,frame:100},{x:350,frame:150},{x:450,frame:150},{x:500,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:35}];k=[{x:270,frame:50},{x:200,frame:150},{x:450,frame:400},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,
frame:40}];v=[{x:190,frame:30},{x:340,frame:170},{x:360,frame:300},{x:380,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:45}];u=[{x:220,frame:100},{x:350,frame:200},{x:400,frame:200},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:50}];r=[{x:210,frame:50},{x:260,frame:300},{x:300,frame:200},{x:220,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:150},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:55}];
p.push({place_1:m,place_2:l,place_3:k,place_4:v,place_5:u,place_6:r});m=[{x:230,frame:50},{x:250,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];l=[{x:250,frame:50},{x:430,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:35}];k=[{x:270,frame:50},{x:330,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:40}];v=[{x:190,frame:50},{x:230,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/
2-390,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:45}];u=[{x:220,frame:50},{x:300,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:50}];r=[{x:210,frame:50},{x:130,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:55}];p.push({place_1:m,place_2:l,place_3:k,place_4:v,place_5:u,place_6:r});m=[{x:210,frame:50},{x:130,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];
l=[{x:220,frame:50},{x:300,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:35}];k=[{x:270,frame:50},{x:330,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:40}];v=[{x:250,frame:50},{x:430,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:45}];u=[{x:190,frame:50},{x:190,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:50}];
r=[{x:230,frame:50},{x:250,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:55}];p.push({place_1:m,place_2:l,place_3:k,place_4:v,place_5:u,place_6:r});m=[{x:330,frame:30},{x:450,frame:180},{x:550,frame:180},{x:650,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];l=[{x:250,frame:90},{x:450,frame:300},{x:600,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:35}];
k=[{x:270,frame:30},{x:400,frame:150},{x:450,frame:210},{x:600,frame:140},{x:500,frame:130},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:40}];v=[{x:290,frame:30},{x:340,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-410,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:45}];u=[{x:220,frame:30},{x:350,frame:280},{x:400,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:50}];r=[{x:310,frame:30},
{x:400,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:55}];p.push({place_1:m,place_2:l,place_3:k,place_4:v,place_5:u,place_6:r})};this._initGreyhoundInfo=function(){h=[];h[0]={start:new createjs.Point(208,342),scale:.66};h[1]={start:new createjs.Point(186,352),scale:.7};h[2]={start:new createjs.Point(163,363),scale:.74};h[3]={start:new createjs.Point(134,376),scale:.8};h[4]={start:new createjs.Point(99,394),scale:.9};h[5]={start:new createjs.Point(53,
415),scale:1}};this.getIndexForFiches=function(m){for(var l=0,k=0;k<d.length;k++)d[k]===m&&(l=k);return l};this.getGreyhoundPercentageArray=function(){for(var m=[],l=0;l<e.length;l++)for(var k=Math.floor(e[l]),v=0;v<k;v++)m.push(l);return m=shuffle(m)};this.getGreyhoundName=function(m){return n[m]};this.getAllGreyhoundNames=function(){return n};this.getOddWin=function(m){return e[m]};this.getOddPlace=function(m){return a[m]};this.getOddShow=function(m){return c[m]};this.getForecastOdd=function(m,
l){return q[m][l]};this.getRandomPath=function(){return p[Math.floor(Math.random()*p.length)]};this.getGreyhoundInfo=function(m){return h[m]};s_oGameSettings=this;this._init(b)}
var s_oGameSettings=null,TEXT_CURRENCY="$",TEXT_START_RACE="START RACE",TEXT_CLEAR_BET="CLEAR BET",TEXT_MONEY="MONEY",TEXT_BET="BET",TEXT_MIN_BET="MIN BET",TEXT_MAX_BET="MAX BET",TEXT_TRAP="TRAP",TEXT_GREYHOUND_NAME="GREYHOUND NAME",TEXT_ODDS="ODDS",TEXT_WINS="WINS",TEXT_PLACE="PLACE",TEXT_SHOW="SHOW",TEXT_WIN="WIN",TEXT_NO_WIN="NO WIN",TEXT_CREDITS_DEVELOPED="DEVELOPED BY",TEXT_NO_MONEY="NOT ENOUGH MONEY!!",TEXT_ERR_MAX_BET="YOUR BET IS HIGHER THAN MAXIMUM ONE!!",TEXT_ERR_MIN_BET="YOUR BET IS LOWER THAN MINIMUM ONE!!",
TEXT_ARE_YOU_SURE="ALL YOUR BETS WILL BE LOST!! ARE YOU SURE?",TEXT_RECHARGE="RECHARGE";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CPreloader(){var b,n,e,a,c,q,d,p,h;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.loadSprites();h=new createjs.Container;s_oStage.addChild(h)};this.unload=function(){h.removeAllChildren()};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};
this.attachSprites=function(){var g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.addChild(g);g=s_oSpriteLibrary.getSprite("200x200");d=createBitmap(g);d.regX=.5*g.width;d.regY=.5*g.height;d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2-80;h.addChild(d);p=new createjs.Shape;p.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(d.x-100,d.y-100,200,200,10);h.addChild(p);d.mask=p;g=s_oSpriteLibrary.getSprite("progress_bar");a=createBitmap(g);a.x=CANVAS_WIDTH/2-g.width/
2;a.y=CANVAS_HEIGHT/2+50;h.addChild(a);b=g.width;n=g.height;c=new createjs.Shape;c.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(a.x,a.y,1,n);h.addChild(c);a.mask=c;e=new createjs.Text("","30px "+PRIMARY_FONT,"#fff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2+100;e.textBaseline="alphabetic";e.textAlign="center";h.addChild(e);q=new createjs.Shape;q.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.addChild(q);createjs.Tween.get(q).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(q);
h.removeChild(q)})};this.refreshLoader=function(g){e.text=g+"%";100===g&&(s_oMain._onRemovePreloader(),e.visible=!1,a.visible=!1);c.graphics.clear();g=Math.floor(g*b/100);c.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(a.x,a.y,g,n)};this._init()}
function CMain(b){var n,e=0,a=0,c=STATE_LOADING,q,d;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage,!0);s_bMobile=isMobile();!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(p){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.framerate=FPS;navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;q=new CPreloader};this.preloaderReady=function(){s_oGameSettings=new CGameSettings(s_oSettingsData);s_oBetList=new CBetList;s_oMain._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_oMain._initSounds();n=!0};this.soundLoaded=function(){e++;q.refreshLoader(Math.floor(e/a*100))};this._initSounds=function(){Howler.mute(!s_bAudioActive);s_aSoundsInfo=[];s_aSoundsInfo.push({path:"./sounds/",filename:"chip",loop:!1,volume:1,ingamename:"chip"});
s_aSoundsInfo.push({path:"./sounds/",filename:"click",loop:!1,volume:1,ingamename:"click"});s_aSoundsInfo.push({path:"./sounds/",filename:"start_race",loop:!1,volume:1,ingamename:"start_race"});s_aSoundsInfo.push({path:"./sounds/",filename:"photo",loop:!1,volume:1,ingamename:"photo"});s_aSoundsInfo.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});a+=s_aSoundsInfo.length;s_aSounds=[];for(var p=0;p<s_aSoundsInfo.length;p++)this.tryToLoadSound(s_aSoundsInfo[p],
!1)};this.tryToLoadSound=function(p,h){setTimeout(function(){s_aSounds[p.ingamename]=new Howl({src:[p.path+p.filename+".mp3"],autoplay:!1,preload:!0,loop:p.loop,volume:p.volume,onload:s_oMain.soundLoaded,onloaderror:function(g,m){for(var l=0;l<s_aSoundsInfo.length;l++)if(g===s_aSounds[s_aSoundsInfo[l].ingamename]._sounds[0]._id){s_oMain.tryToLoadSound(s_aSoundsInfo[l],!0);break}},onplayerror:function(g){for(var m=0;m<s_aSoundsInfo.length;m++)if(g===s_aSounds[s_aSoundsInfo[m].ingamename]._sounds[0]._id){s_aSounds[s_aSoundsInfo[m].ingamename].once("unlock",
function(){s_aSounds[s_aSoundsInfo[m].ingamename].play();"soundtrack"===s_aSoundsInfo[m].ingamename&&null!==s_oGame&&setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME)});break}}})},h?200:0)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_play",
"./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_no","./sprites/but_no.png");s_oSpriteLibrary.addSprite("but_yes",
"./sprites/but_yes.png");s_oSpriteLibrary.addSprite("arrow_left","./sprites/arrow_left.png");s_oSpriteLibrary.addSprite("arrow_right","./sprites/arrow_right.png");s_oSpriteLibrary.addSprite("fiche_0","./sprites/fiche_0.png");s_oSpriteLibrary.addSprite("fiche_1","./sprites/fiche_1.png");s_oSpriteLibrary.addSprite("fiche_2","./sprites/fiche_2.png");s_oSpriteLibrary.addSprite("fiche_3","./sprites/fiche_3.png");s_oSpriteLibrary.addSprite("fiche_4","./sprites/fiche_4.png");s_oSpriteLibrary.addSprite("fiche_5",
"./sprites/fiche_5.png");s_oSpriteLibrary.addSprite("bg_bet_panel","./sprites/bg_bet_panel.jpg");s_oSpriteLibrary.addSprite("money_panel","./sprites/money_panel.png");s_oSpriteLibrary.addSprite("simple_bet_panel","./sprites/simple_bet_panel.png");s_oSpriteLibrary.addSprite("forecast_panel","./sprites/forecast_panel.png");s_oSpriteLibrary.addSprite("bet_place","./sprites/bet_place.png");s_oSpriteLibrary.addSprite("fiche_highlight","./sprites/fiche_highlight.png");s_oSpriteLibrary.addSprite("odd_bg",
"./sprites/odd_bg.png");s_oSpriteLibrary.addSprite("rank_panel","./sprites/rank_panel.png");s_oSpriteLibrary.addSprite("panel_arrival","./sprites/panel_arrival.png");s_oSpriteLibrary.addSprite("bibs","./sprites/bibs.png");s_oSpriteLibrary.addSprite("but_skip","./sprites/but_skip.png");s_oSpriteLibrary.addSprite("logo_menu","./sprites/logo_menu.png");s_oSpriteLibrary.addSprite("but_start_race","./sprites/but_start_race.png");s_oSpriteLibrary.addSprite("but_clear_bet","./sprites/but_clear_bet.png");
s_oSpriteLibrary.addSprite("fiche_panel","./sprites/fiche_panel.png");s_oSpriteLibrary.addSprite("fill_bar","./sprites/fill_bar.png");s_oSpriteLibrary.addSprite("win_panel","./sprites/win_panel.png");s_oSpriteLibrary.addSprite("lose_panel","./sprites/lose_panel.png");for(var p=0;p<NUM_GREYHOUNDS;p++)s_oSpriteLibrary.addSprite("bib_gui_"+p,"./sprites/bib_gui_"+p+".png"),s_oSpriteLibrary.addSprite("greyhound_"+(p+1),"./sprites/greyhound_"+(p+1)+".png");for(p=0;p<NUM_TRACK_BG;p++)s_oSpriteLibrary.addSprite("bg_track_"+
p,"./sprites/bg_track/bg_track_"+p+".jpg");a+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){e++;q.refreshLoader(Math.floor(e/a*100))};this._onAllImagesLoaded=function(){};this._onRemovePreloader=function(){try{saveItem("ls_available","ok")}catch(p){s_bStorageAvailable=!1}q.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=playSound("soundtrack",1,!0);this.gotoMenu()};this.gotoMenu=function(){new CMenu;c=STATE_MENU};this.gotoBetPanel=
function(){new CBetPanel;c=STATE_BET_PANEL;$(s_oMain).trigger("start_session")};this.gotoGame=function(p){d=new CGame(p);c=STATE_GAME};this.stopUpdate=function(){n=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();n=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};
this._update=function(p){if(!1!==n){var h=(new Date).getTime();s_iTimeElaps=h-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=h;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);c===STATE_GAME&&d.update();s_oStage.update(p)}};s_oMain=this;s_iCurMoney=b.money;s_iGameCash=b.game_cash;CHIP_VALUES=b.chip_values;MIN_BET=b.min_bet;MAX_BET=b.max_bet;WIN_OCCURRENCE=b.win_occurrence;AD_SHOW_COUNTER=b.num_levels_for_ads;SHOW_CREDITS=b.show_credits;ENABLE_FULLSCREEN=b.fullscreen;
ENABLE_CHECK_ORIENTATION=b.check_orientation;NUM_CHIPS=CHIP_VALUES.length;s_bAudioActive=b.audio_enable_on_startup;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_bFullscreen=!1,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack=null,s_oCanvas,s_bStorageAvailable=!0,s_iCurMoney,s_iGameCash,s_iAdCounter=0,s_aSounds,s_aSoundsInfo;
function CTextButton(b,n,e,a,c,q,d,p){var h,g,m,l,k,v,u,r,x,C;this._init=function(f,w,y,z,E,M,D){h=!1;g=1;m=[];l=[];C=createBitmap(y);r=new createjs.Container;r.x=f;r.y=w;r.regX=y.width/2;r.regY=y.height/2;s_bMobile||(r.cursor="pointer");r.addChild(C,x);p.addChild(r);x=new CTLText(r,0,0,y.width,y.height,D,"center",M,E,1,2,2,z,!0,!0,!1,!1);this._initListener()};this.unload=function(){r.off("mousedown",k);r.off("pressup",v);p.removeChild(r)};this.setVisible=function(f){r.visible=f};this.setAlign=function(f){x.textAlign=
f};this.setTextX=function(f){x.x=f};this.setScale=function(f){g=r.scaleX=r.scaleY=f};this.enable=function(){h=!1};this.disable=function(){h=!0};this._initListener=function(){k=r.on("mousedown",this.buttonDown);v=r.on("pressup",this.buttonRelease)};this.addEventListener=function(f,w,y){m[f]=w;l[f]=y};this.addEventListenerWithParams=function(f,w,y,z){m[f]=w;l[f]=y;u=z};this.buttonRelease=function(){h||(playSound("click",1,!1),r.scaleX=g,r.scaleY=g,m[ON_MOUSE_UP]&&m[ON_MOUSE_UP].call(l[ON_MOUSE_UP],
u))};this.buttonDown=function(){h||(r.scaleX=.9*g,r.scaleY=.9*g,m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN]))};this.setPosition=function(f,w){r.x=f;r.y=w};this.tweenPosition=function(f,w,y,z,E,M,D){createjs.Tween.get(r).wait(z).to({x:f,y:w},y,E).call(function(){void 0!==M&&M.call(D)})};this.changeText=function(f){x.refreshText(f)};this.setX=function(f){r.x=f};this.setY=function(f){r.y=f};this.getButtonImage=function(){return r};this.getX=function(){return r.x};this.getY=function(){return r.y};
this.getSprite=function(){return r};this.getScale=function(){return r.scaleX};this._init(b,n,e,a,c,q,d)}
function CToggle(b,n,e,a,c){var q,d,p,h,g,m,l;this._init=function(k,v,u,r,x){l=void 0!==x?x:s_oStage;d=[];p=[];x=new createjs.SpriteSheet({images:[u],frames:{width:u.width/2,height:u.height,regX:u.width/2/2,regY:u.height/2},animations:{state_true:[0],state_false:[1]}});q=r;h=createSprite(x,"state_"+q,u.width/2/2,u.height/2,u.width/2,u.height);h.x=k;h.y=v;h.stop();s_bMobile||(h.cursor="pointer");l.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",g);h.off("pressup",m);l.removeChild(h)};
this._initListener=function(){g=h.on("mousedown",this.buttonDown);m=h.on("pressup",this.buttonRelease)};this.addEventListener=function(k,v,u){d[k]=v;p[k]=u};this.setCursorType=function(k){h.cursor=k};this.setActive=function(k){q=k;h.gotoAndStop("state_"+q)};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;playSound("click",1,0);q=!q;h.gotoAndStop("state_"+q);d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(p[ON_MOUSE_UP],q)};this.buttonDown=function(){h.scaleX=.9;h.scaleY=.9;d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN])};
this.setPosition=function(k,v){h.x=k;h.y=v};this._init(b,n,e,a,c)}
function CGfxButton(b,n,e,a){var c,q,d,p,h,g,m,l,k=!1;this._init=function(r,x,C){c=[];q=[];p=[];d=createBitmap(C);d.x=r;d.y=x;g=h=1;d.regX=C.width/2;d.regY=C.height/2;s_bMobile||(d.cursor="pointer");v.addChild(d);this._initListener()};this.unload=function(){d.off("mousedown",m);d.off("pressup",l);v.removeChild(d)};this.setVisible=function(r){d.visible=r};this.setCursorType=function(r){d.cursor=r};this._initListener=function(){m=d.on("mousedown",this.buttonDown);l=d.on("pressup",this.buttonRelease)};
this.addEventListener=function(r,x,C){c[r]=x;q[r]=C};this.addEventListenerWithParams=function(r,x,C,f){c[r]=x;q[r]=C;p[r]=f};this.buttonRelease=function(){k||(d.scaleX=0<h?h:-h,d.scaleY=g,playSound("click",1,0),c[ON_MOUSE_UP]&&c[ON_MOUSE_UP].call(q[ON_MOUSE_UP],p[ON_MOUSE_UP]))};this.buttonDown=function(){k||(d.scaleX=0<h?.9*h:.9*-h,d.scaleY=.9*g,c[ON_MOUSE_DOWN]&&c[ON_MOUSE_DOWN].call(q[ON_MOUSE_DOWN],p[ON_MOUSE_DOWN]))};this.rotation=function(r){d.rotation=r};this.getButton=function(){return d};
this.setPosition=function(r,x){d.x=r;d.y=x};this.setX=function(r){d.x=r};this.setY=function(r){d.y=r};this.getButtonImage=function(){return d};this.block=function(r){k=r;d.scaleX=h;d.scaleY=g};this.setScaleX=function(r){h=d.scaleX=r};this.setScale=function(r){g=h=r;d.scaleX=d.scaleY=r};this.getX=function(){return d.x};this.getY=function(){return d.y};this.pulseAnimation=function(){createjs.Tween.get(d).to({scaleX:.9*h,scaleY:.9*g},850,createjs.Ease.quadOut).to({scaleX:h,scaleY:g},650,createjs.Ease.quadIn).call(function(){u.pulseAnimation()})};
this.trebleAnimation=function(){createjs.Tween.get(d).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){u.trebleAnimation()})};this.removeAllTweens=function(){createjs.Tween.removeTweens(d)};var v=void 0!==a?a:s_oStage;this._init(b,n,e);var u=this;return this}
function CMenu(){var b,n,e,a,c,q,d,p,h,g,m,l,k,v,u,r=null,x,C=null,f=null,w;this._init=function(){m=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(m);var y=s_oSpriteLibrary.getSprite("but_play");h=CANVAS_WIDTH/2;g=CANVAS_HEIGHT-y.height/2-10;l=new CGfxButton(h,g,y);l.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);y=s_oSpriteLibrary.getSprite("but_credits");SHOW_CREDITS?(c=10+y.width/2,q=y.height/2+10,u=new CGfxButton(c,q,y),u.addEventListener(ON_MOUSE_UP,this._onCredits,
this),e=c+y.width+10,a=q):(e=10+y.width/2,a=y.height/2+10);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)y=s_oSpriteLibrary.getSprite("audio_icon"),d=CANVAS_WIDTH-y.width/4-10,p=y.height/2+10,v=new CToggle(d,p,y,s_bAudioActive,s_oStage),v.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);y=window.document;var z=y.documentElement;C=z.requestFullscreen||z.mozRequestFullScreen||z.webkitRequestFullScreen||z.msRequestFullscreen;f=y.exitFullscreen||y.mozCancelFullScreen||y.webkitExitFullscreen||y.msExitFullscreen;
!1===ENABLE_FULLSCREEN&&(C=!1);C&&!1===inIframe()&&(y=s_oSpriteLibrary.getSprite("but_fullscreen"),x=new CToggle(e,a,y,s_bFullscreen,s_oStage),x.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));y=s_oSpriteLibrary.getSprite("logo_menu");b=CANVAS_WIDTH/2;n=10;w=createBitmap(y);w.regX=y.width/2;w.x=b;w.y=n;s_oStage.addChild(w);k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(k);createjs.Tween.get(k).to({alpha:0},1E3).call(function(){s_oStage.removeChild(k)});
this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){l.unload();l=null;SHOW_CREDITS&&u.unload();s_oStage.removeChild(m);m=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)v.unload(),v=null;C&&!1===inIframe()&&x.unload();s_oMenu=null};this.refreshButtonPos=function(y,z){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||v.setPosition(d-y,p+z);C&&!1===inIframe()&&x.setPosition(e+y,a+z);l.setPosition(h,g-z);SHOW_CREDITS&&u.setPosition(c+y,q+z);null!==r&&r.refreshButtonPos(y,z);w.y=n+z};this.exitFromCredits=
function(){r=null};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onCredits=function(){r=new CCreditsPanel};this._onButPlayRelease=function(){this.unload();s_oMain.gotoBetPanel()};this.resetFullscreenBut=function(){C&&screenfull.isEnabled&&x.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?f.call(window.document):C.call(window.document.documentElement);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(b){var n,e,a,c,q,d,p,h,g,m,l,k,v,u,r,x,C;this._init=function(){c=a=n=!1;p=d=0;l=s_oGameSettings.getAllGreyhoundNames();setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME);s_oTweenController=new CTweenController;k=new createjs.Container;s_oStage.addChild(k);u=new CTrackBg(k);x=new CRankingGui(l,s_oStage);C=new CArrivalPanel(CANVAS_WIDTH,240,s_oStage);r=new CInterface;this.generateFinalRank();this._prepareGreyHounds();v=new createjs.Shape;v.graphics.beginFill("white").drawRect(0,0,CANVAS_WIDTH,
CANVAS_HEIGHT);v.alpha=0;s_oStage.addChild(v);$(s_oMain).trigger("start_level",1);setTimeout(function(){s_oGame.startRace()},1E3);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){stopSound("start_race");r.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren();s_oGame=null};this.refreshButtonPos=function(f,w){r.refreshButtonPos(f,w);x.refreshButtonPos(f,w)};this.pause=function(){n=!1;pauseSound("start_race");for(var f=0;f<NUM_GREYHOUNDS;f++)m[f].pauseAnim()};this.unpause=
function(){n=!0;playSound("start_race");for(var f=0;f<NUM_GREYHOUNDS;f++)m[f].unpauseAnim()};this.onExit=function(){setVolume("soundtrack",1);s_oGame.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_session");$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("share_event",[s_iCurMoney])};this.gotoBetPanel=function(){setVolume("soundtrack",1);s_oGame.unload();s_oMain.gotoBetPanel()};this.startRace=function(){playSound("start_race",1,0);r.blockExit(!1);n=!0};this.generateFinalRank=function(){s_oBetList.getMinWin()>
s_iGameCash?this._generateLosingResult():100*Math.random()<WIN_OCCURRENCE?this._generateWinResult():this._generateLosingResult()};this._generateWinResult=function(){e=!0;do{h=this._generateRandomRank();var f=s_oBetList.getTotWinWithCurRank(h);q=f.tot_win}while(q<=b);g=f.win_list};this._generateLosingResult=function(){e=!1;do{h=this._generateRandomRank();var f=s_oBetList.getTotWinWithCurRank(h);q=f.tot_win}while(q>b);g=f.win_list};this._generateRandomRank=function(){for(var f=[],w=s_oGameSettings.getGreyhoundPercentageArray();f.length<
NUM_GREYHOUNDS;){var y=w[Math.floor(Math.random()*w.length)];f.unshift(y);for(var z=w.length-1;0<=z;)w[z]===y&&w.splice(z,1),z--}return f};this._prepareGreyHounds=function(){m=[];for(var f=s_oGameSettings.getRandomPath(),w=0;w<NUM_GREYHOUNDS;w++){var y=s_oGameSettings.getGreyhoundInfo(w),z=h.indexOf(w);m[w]=new CGreyhound(y.start,w+1,l[w],y.scale,f["place_"+(z+1)],k)}};this.startGreyhounds=function(){for(var f=0;f<NUM_GREYHOUNDS;f++)m[f].startRace()};this.greyhoundPhotofinish=function(f,w){r.blockExit(!0);
C.refreshRank(f,w);d++;4>d?(n=!1,p=TIME_CHECK_RANK,this._playFlashAnim()):6===d&&(e||0<q?(s_iCurMoney+=q,s_iCurMoney=parseFloat(s_iCurMoney.toFixed(2)),s_iGameCash-=q,s_iGameCash=parseFloat(s_iGameCash.toFixed(2)),r.showWinPanel(q,g,h)):r.showLosePanel(h),stopSound("start_race"),setVolume("soundtrack",1),$(s_oMain).trigger("save_score",s_iCurMoney))};this.checkGreyhoundArrival=function(){a=!0};this._playFlashAnim=function(){for(var f=0;f<NUM_GREYHOUNDS;f++)m[f].pauseAnim();playSound("photo",1,0);
createjs.Tween.get(v).to({alpha:.8},200).call(function(){var w=(new createjs.ColorMatrix).adjustSaturation(-100);k.filters=[new createjs.ColorMatrixFilter(w)];k.cache(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c=!0;createjs.Tween.get(v).to({alpha:0},400).call(function(){s_oGame.restoreRaceAfterFlash()})})};this.restoreRaceAfterFlash=function(){setTimeout(function(){for(var f=0;f<NUM_GREYHOUNDS;f++)m[f].unpauseAnim();k.filters=[];k.cache(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);n=!0},1E3)};this._refreshRank=function(){for(var f=
[],w=0;w<NUM_GREYHOUNDS;w++){var y=m[w].getX();f[w]={index:w,x:y}}f.sort(this.compareXPos);x.refreshRank(f)};this.compareXPos=function(f,w){return f.x>w.x?-1:f.x<w.x?1:0};this.returnInBetPanel=function(){s_iAdCounter++;s_iAdCounter===AD_SHOW_COUNTER&&(s_iAdCounter=0,$(s_oMain).trigger("show_interlevel_ad"));s_oGame.gotoBetPanel()};this.update=function(){if(n){var f=u.update();x.refreshRadar(f-16);for(f=0;f<NUM_GREYHOUNDS;f++)m[f].update(a);c&&k.updateCache();p+=s_iTimeElaps;p>TIME_CHECK_RANK&&!a&&
(p=0,this._refreshRank())}};s_oGame=this;this._init()}var s_oGame=null,s_oTweenController;
function CInterface(){var b,n,e,a,c,q,d,p,h=null,g=null,m,l,k,v;this._init=function(){var u=s_oSpriteLibrary.getSprite("but_exit");b=CANVAS_WIDTH-u.width/2-10;n=u.height/2+10;m=new CGfxButton(b,n,u);m.block(!0);m.addEventListener(ON_MOUSE_UP,this._onExit,this);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(u=s_oSpriteLibrary.getSprite("audio_icon"),c=b-u.width/2-10,q=n,d=new CToggle(c,q,u,s_bAudioActive,s_oStage),d.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),e=c-u.width/2-10,a=q):(e=b-u.width-
10,a=n);u=window.document;var r=u.documentElement;h=r.requestFullscreen||r.mozRequestFullScreen||r.webkitRequestFullScreen||r.msRequestFullscreen;g=u.exitFullscreen||u.mozCancelFullScreen||u.webkitExitFullscreen||u.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(h=!1);h&&!1===inIframe()&&(u=s_oSpriteLibrary.getSprite("but_fullscreen"),p=new CToggle(e,a,u,s_bFullscreen,s_oStage),p.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));k=new CLosePanel(s_oStage);l=new CWinPanel(s_oStage);v=new CAreYouSurePanel(s_oStage)};
this.refreshButtonPos=function(u,r){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||d.setPosition(c-u,q+r);h&&!1===inIframe()&&p.setPosition(e-u,a+r);m.setPosition(b-u,n+r)};this.showWinPanel=function(u,r,x){l.show(u,r,x)};this.showLosePanel=function(u){k.show(u)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)d.unload(),d=null;h&&!1===inIframe()&&p.unload();l.unload();k.unload();v.unload();s_oInterface=null};this.blockExit=function(u){m.block(u)};this._onExit=function(){s_oGame.pause();
v.show()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){h&&screenfull.isEnabled&&p.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?g.call(window.document):h.call(window.document.documentElement);sizeHandler()};this._onFullscreenRelease=function(){s_bFullscreen?g.call(window.document):h.call(window.document.documentElement);sizeHandler()};s_oInterface=this;this._init();return this}
var s_oInterface=null;
function CCreditsPanel(){var b,n,e,a,c,q,d,p,h,g;this._init=function(){g=new createjs.Container;s_oStage.addChild(g);b=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));g.addChild(b);q=new createjs.Shape;q.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);q.alpha=.01;h=q.on("click",this._onLogoButRelease);g.addChild(q);var m=s_oSpriteLibrary.getSprite("but_exit");e=new CGfxButton(715,250,m,g);e.addEventListener(ON_MOUSE_UP,this.unload,this);c=new createjs.Text(TEXT_CREDITS_DEVELOPED,"40px "+
PRIMARY_FONT,"#000");c.textAlign="center";c.textBaseline="alphabetic";c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2-60;c.outline=4;g.addChild(c);a=new createjs.Text(TEXT_CREDITS_DEVELOPED,"40px "+PRIMARY_FONT,"#fff");a.textAlign="center";a.textBaseline="alphabetic";a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2-60;g.addChild(a);m=s_oSpriteLibrary.getSprite("logo_ctl");n=createBitmap(m);n.regX=m.width/2;n.regY=m.height/2;n.x=CANVAS_WIDTH/2;n.y=CANVAS_HEIGHT/2;g.addChild(n);p=new createjs.Text("www.codethislab.com",
"36px "+PRIMARY_FONT,"#000");p.textAlign="center";p.textBaseline="alphabetic";p.x=CANVAS_WIDTH/2;p.y=CANVAS_HEIGHT/2+80;p.outline=4;g.addChild(p);d=new createjs.Text("www.codethislab.com","36px "+PRIMARY_FONT,"#fff");d.textAlign="center";d.textBaseline="alphabetic";d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2+80;g.addChild(d)};this.unload=function(){q.off("click",h);e.unload();e=null;s_oStage.removeChild(g);s_oMenu.exitFromCredits()};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en",
"_blank")};this._init()}
function CBetPanel(){var b,n,e,a,c,q,d,p,h,g,m,l,k,v,u,r,x,C;this._init=function(){d=c=0;h=[];C=new createjs.Container;s_oStage.addChild(C);var f=createBitmap(s_oSpriteLibrary.getSprite("bg_bet_panel"));C.addChild(f);f=s_oSpriteLibrary.getSprite("but_exit");e=CANVAS_WIDTH-f.width/2-10;a=f.height/2+10;u=new CGfxButton(e,a,f,C);u.addEventListener(ON_MOUSE_UP,this.onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var w=s_oSpriteLibrary.getSprite("audio_icon");b=e-f.width-10;n=w.height/2+10;
r=new CToggle(b,n,w,s_bAudioActive,s_oStage);r.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this)}f=s_oSpriteLibrary.getSprite("simple_bet_panel");BET_PANEL_WIDTH=f.width;BET_PANEL_HEIGHT=f.height;x=new createjs.Container;x.x=BET_PANEL_X;x.y=BET_PANEL_Y;C.addChild(x);p=[];p[0]=new CSimpleBetPanel(0,0,x);p[1]=new CForecastPanel(BET_PANEL_WIDTH,0,x);k=new CChipPanel(800,263,C);g=new createjs.Shape;g.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(BET_PANEL_X+6,BET_PANEL_Y,BET_PANEL_WIDTH-
12,BET_PANEL_HEIGHT);C.addChild(g);x.mask=g;q=0;m=new CGfxButton(BET_PANEL_X+7,CANVAS_HEIGHT/2,s_oSpriteLibrary.getSprite("arrow_left"),C);m.addEventListener(ON_MOUSE_UP,this._onArrowLeft,this);l=new CGfxButton(BET_PANEL_X+f.width-7,CANVAS_HEIGHT/2,s_oSpriteLibrary.getSprite("arrow_right"),C);l.addEventListener(ON_MOUSE_UP,this._onArrowRight,this);v=new CMsgBox;s_oBetList.reset();this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){m.unload();l.unload();u.unload();!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||r.unload();v.unload();k.unload();for(var f=0;f<p.length;f++)p[f].unload();s_oStage.removeAllChildren()};this.refreshButtonPos=function(f,w){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||r.setPosition(b-f,n+w);u.setPosition(e-f,a+w)};this.setChipSelected=function(f){d=f};this.setMoney=function(f){s_iCurMoney=f;k.refreshMoney()};this.setSimpleBet=function(f,w,y,z){if(y>s_iCurMoney)return v.show(TEXT_NO_MONEY,!0),!1;if(c+y>MAX_BET)return v.show(TEXT_ERR_MAX_BET,!1),!1;s_oBetList.addSimpleBet(f,
w,y);c+=y;c=Number(c.toFixed(2));s_iCurMoney-=y;s_iCurMoney=parseFloat(s_iCurMoney.toFixed(2));s_iGameCash+=y;s_iGameCash=parseFloat(s_iGameCash.toFixed(2));k.refreshMoney();k.refreshBet(c);h.push(z);return!0};this.setForecastBet=function(f,w,y,z){if(y>s_iCurMoney)return v.show(TEXT_NO_MONEY,!0),!1;if(c+y>MAX_BET)return v.show(TEXT_ERR_MAX_BET,!1),!1;s_oBetList.addForecastBet(f,w,y);c+=y;c=Number(c.toFixed(2));s_iCurMoney-=y;s_iCurMoney=parseFloat(s_iCurMoney.toFixed(2));s_iGameCash+=y;s_iGameCash=
parseFloat(s_iGameCash.toFixed(2));k.refreshMoney();k.refreshBet(c);h.push(z);return!0};this.refreshPagePos=function(f,w){x.x=BET_PANEL_X;p[q].setX(0);p[f].setX(w)};this.clearBet=function(){for(var f=0;f<h.length;f++)h[f].clearBet();s_iCurMoney+=c;s_iCurMoney=parseFloat(s_iCurMoney.toFixed(2));s_iGameCash-=c;s_iGameCash=parseFloat(s_iGameCash.toFixed());c=0;p[0].clearBet();s_oBetList.reset();k.refreshBet(0);k.refreshMoney()};this._onArrowLeft=function(){var f=q;q++;q===p.length&&(q=0,f=p.length-1);
p[q].setX(BET_PANEL_WIDTH);createjs.Tween.get(x).to({x:-BET_PANEL_WIDTH+BET_PANEL_X},500,createjs.Ease.cubicOut).call(function(){s_oBetPanel.refreshPagePos(f,BET_PANEL_WIDTH)})};this._onArrowRight=function(){var f=q;q--;0>q&&(q=p.length-1);p[q].setX(-BET_PANEL_WIDTH);createjs.Tween.get(x).to({x:BET_PANEL_X+BET_PANEL_WIDTH},500,createjs.Ease.cubicOut).call(function(){s_oBetPanel.refreshPagePos(f,-BET_PANEL_WIDTH)})};this.onStartExit=function(){c<MIN_BET?v.show(TEXT_ERR_MIN_BET,!1):(this.unload(),s_oMain.gotoGame(c),
$(s_oMain).trigger("bet_placed",c))};this.onExit=function(){$(s_oMain).trigger("end_session");this.unload();s_oMain.gotoMenu()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.getChipSelected=function(){return d};s_oBetPanel=this;this._init()}var s_oBetPanel=null;
function CChipPanel(b,n,e){var a,c,q,d,p,h,g;this._init=function(l,k){g=new createjs.Container;g.x=l;g.y=k;m.addChild(g);h=new CTextButton(73,2,s_oSpriteLibrary.getSprite("but_clear_bet"),TEXT_CLEAR_BET,PRIMARY_FONT,"#fff",24,g);h.addEventListener(ON_MOUSE_UP,this._onClearBet,this);var v=s_oSpriteLibrary.getSprite("money_panel"),u=createBitmap(s_oSpriteLibrary.getSprite("money_panel"));u.regX=v.width/2;u.x=73;u.y=22;g.addChild(u);new CTLText(g,18,30,110,14,14,"center","#ffde00",SECONDARY_FONT,1,0,
0,TEXT_MIN_BET+": "+MIN_BET+TEXT_CURRENCY,!0,!0,!1,!1);new CTLText(g,18,44,110,14,14,"center","#ffde00",SECONDARY_FONT,1,0,0,TEXT_MAX_BET+": "+MAX_BET+TEXT_CURRENCY,!0,!0,!1,!1);u=createBitmap(s_oSpriteLibrary.getSprite("money_panel"));u.regX=v.width/2;u.x=73;u.y=72;g.addChild(u);new CTLText(g,3,75,100,11,11,"left","#fff",TERTIARY_FONT,1,0,0,TEXT_BET,!0,!0,!1,!1);d=new CTLText(g,18,82,110,26,26,"center","#ffde00",SECONDARY_FONT,1,0,0,"0"+TEXT_CURRENCY,!0,!0,!1,!1);u=createBitmap(v);u.regX=v.width/
2;u.x=73;u.y=122;g.addChild(u);new CTLText(g,3,125,100,11,11,"left","#fff",TERTIARY_FONT,1,0,0,TEXT_MONEY,!0,!0,!1,!1);q=new CTLText(g,18,132,110,26,26,"center","#ffde00",SECONDARY_FONT,1,0,0,s_iCurMoney+TEXT_CURRENCY,!0,!0,!1,!1);this._initChips();p=new CButStartRace(73,304,s_oSpriteLibrary.getSprite("but_start_race"),TEXT_START_RACE,"#fff",24,g);p.addEventListener(ON_MOUSE_UP,this._onStartRace,this)};this.unload=function(){for(var l=0;l<a;l++)a[l].unload();p.unload()};this._initChips=function(){var l=
createBitmap(s_oSpriteLibrary.getSprite("fiche_panel"));l.x=0;l.y=170;g.addChild(l);l=[{x:25,y:198},{x:76,y:198},{x:124,y:198},{x:25,y:242},{x:76,y:242},{x:124,y:242}];a=[];for(var k=0;k<NUM_CHIPS;k++)a[k]=new CFicheBut(k,l[k].x,l[k].y,1,g),a[k].addEventListenerWithParams(ON_MOUSE_UP,this._onFicheClicked,this,k);l=s_oSpriteLibrary.getSprite("fiche_highlight");c=createBitmap(l);c.regX=l.width/2;c.regY=l.height/2;c.x=a[0].getX()-1;c.y=a[0].getY()-1;g.addChild(c)};this.refreshMoney=function(){q.refreshText(s_iCurMoney+
TEXT_CURRENCY)};this.refreshBet=function(l){d.refreshText(l+TEXT_CURRENCY)};this._onStartRace=function(){s_oBetPanel.onStartExit()};this._onClearBet=function(){s_oBetPanel.clearBet()};this._onFicheClicked=function(l){c.x=a[l].getX()-1;c.y=a[l].getY()-1;s_oBetPanel.setChipSelected(l)};var m=e;this._init(b,n)}
function CSimpleBetPanel(b,n,e){var a,c,q,d,p;this._init=function(g,m){p=new createjs.Container;p.x=g;p.y=m;h.addChild(p);var l=createBitmap(s_oSpriteLibrary.getSprite("simple_bet_panel"));p.addChild(l);new CTLText(p,0,7,100,20,20,"center","#fff",PRIMARY_FONT,1,0,0,TEXT_TRAP,!0,!0,!1,!1);new CTLText(p,110,7,180,20,20,"center","#fff",PRIMARY_FONT,1,0,0,TEXT_GREYHOUND_NAME,!0,!0,!1,!1);new CTLText(p,295,7,140,20,20,"center","#fff",PRIMARY_FONT,1,0,0,TEXT_WINS,!0,!0,!1,!1);new CTLText(p,442,7,120,20,
20,"center","#fff",PRIMARY_FONT,1,0,0,TEXT_PLACE,!0,!0,!1,!1);new CTLText(p,570,7,120,20,20,"center","#fff",PRIMARY_FONT,1,0,0,TEXT_SHOW,!0,!0,!1,!1);l=s_oSpriteLibrary.getSprite("bibs");for(var k=new createjs.SpriteSheet({images:[l],frames:{width:l.width/3,height:l.height/2},animations:{bib_0:[0],bib_1:[1],bib_2:[2],bib_3:[3],bib_4:[4],bib_5:[5]}}),v=38,u=0;u<NUM_GREYHOUNDS;u++){var r=createSprite(k,"bib_"+u,0,0,l.width/3,l.height/2);r.x=28;r.y=v;p.addChild(r);v+=l.height/2+11}this._initGreyhoundInfos();
this._initBetPlaces()};this._initGreyhoundInfos=function(){var g=s_oGameSettings.getAllGreyhoundNames();a=[];for(var m=104,l=0;l<NUM_GREYHOUNDS;l++){var k={framerate:40,images:[s_oSpriteLibrary.getSprite("greyhound_"+(l+1))],frames:{width:GREYHOUND_WIDTH,height:GREYHOUND_HEIGHT,regX:GREYHOUND_WIDTH/2,regY:GREYHOUND_HEIGHT},animations:{idle:[0,0],anim:[0,21],start:[22],anim_1:[5,21,"anim"],anim_2:[10,21,"anim"],anim_3:[15,21,"anim"]}};k=new createjs.SpriteSheet(k);k=createSprite(k,"idle",GREYHOUND_WIDTH/
2,GREYHOUND_HEIGHT,GREYHOUND_WIDTH,GREYHOUND_HEIGHT);k.x=150;k.y=m;k.scaleX=k.scaleY=.5;p.addChild(k);a.push(k);new CTLText(p,168,m-22,120,14,14,"right","#fff",TERTIARY_FONT,1,0,0,g[l].toUpperCase(),!0,!0,!1,!1);m+=67}};this._initBetPlaces=function(){q=[];d=[];c=[];for(var g=66,m=s_oSpriteLibrary.getSprite("bet_place"),l=0;l<NUM_GREYHOUNDS;l++){var k=new createjs.Text(s_oGameSettings.getOddWin(l),"20px "+TERTIARY_FONT,"#fff");k.textAlign="center";k.textBaseline="middle";k.x=325;k.y=g;p.addChild(k);
k=new CButBet(k.x+60,g,m,.7,p);k.addEventListenerWithParams(ON_MOUSE_UP,this._onWinClicked,this,l);c.push(k);k=new createjs.Text(s_oGameSettings.getOddPlace(l),"20px "+TERTIARY_FONT,"#fff");k.textAlign="center";k.textBaseline="middle";k.x=465;k.y=g;p.addChild(k);k=new CButBet(k.x+60,g,m,.7,p);k.addEventListenerWithParams(ON_MOUSE_UP,this._onPlaceClicked,this,l);q.push(k);k=new createjs.Text(s_oGameSettings.getOddShow(l),"20px "+TERTIARY_FONT,"#fff");k.textAlign="center";k.textBaseline="middle";k.x=
593;k.y=g;p.addChild(k);k=new CButBet(k.x+60,g,m,.7,p);k.addEventListenerWithParams(ON_MOUSE_UP,this._onShowClicked,this,l);d.push(k);g+=67}};this.unload=function(){for(var g=0;g<q.length;g++)c[g].unload(),d[g].unload(),q[g].unload()};this.setX=function(g){p.x=g};this.clearBet=function(){for(var g=0;g<a.length;g++)a[g].gotoAndStop("idle")};this._onWinClicked=function(g){var m=CHIP_VALUES[s_oBetPanel.getChipSelected()];s_oBetPanel.setSimpleBet(g,1,m,c[g])&&(0===c[g].getTotBet()&&a[g].gotoAndPlay("anim"),
c[g].increaseBet(m))};this._onPlaceClicked=function(g){var m=CHIP_VALUES[s_oBetPanel.getChipSelected()];s_oBetPanel.setSimpleBet(g,2,m,q[g])&&(0===q[g].getTotBet()&&a[g].gotoAndPlay("anim"),q[g].increaseBet(m))};this._onShowClicked=function(g){var m=CHIP_VALUES[s_oBetPanel.getChipSelected()];s_oBetPanel.setSimpleBet(g,3,m,d[g])&&(0===d[g].getTotBet()&&a[g].gotoAndPlay("anim"),d[g].increaseBet(m))};this.getContainer=function(){return p};var h=e;this._init(b,n)}
function CForecastPanel(b,n,e){var a,c;this._init=function(){c=new createjs.Container;c.x=b;c.y=n;q.addChild(c);var d=createBitmap(s_oSpriteLibrary.getSprite("forecast_panel"));c.addChild(d);this._initForecastBets()};this.unload=function(){for(var d in a)-1<d.indexOf("forecast_")&&a[d].unload()};this._initForecastBets=function(){a=[];for(var d=[{x:26,y:10},{x:256,y:10},{x:486,y:10},{x:26,y:225},{x:256,y:225},{x:486,y:225}],p=0;p<NUM_GREYHOUNDS;p++)this._placeForecastBetForGreyhound(p,d[p].x,d[p].y)};
this._placeForecastBetForGreyhound=function(d,p,h){var g=s_oSpriteLibrary.getSprite("odd_bg"),m=s_oSpriteLibrary.getSprite("bet_place"),l=s_oSpriteLibrary.getSprite("bibs"),k=l.width/3,v=l.height/2;l=new createjs.SpriteSheet({images:[l],frames:{width:k,height:v},animations:{bib_0:[0],bib_1:[1],bib_2:[2],bib_3:[3],bib_4:[4],bib_5:[5]}});for(var u=0;u<NUM_GREYHOUNDS;u++)if(u!==d){var r=createSprite(l,"bib_"+d,0,0,k,v);r.x=p;r.y=h;r.scaleX=r.scaleY=.65;c.addChild(r);var x=new createjs.Text("X","12px "+
PRIMARY_FONT,"#fff");x.textAlign="center";x.textBaseline="middle";x.x=p+.65*k+10;x.y=h+.65*v/2;c.addChild(x);var C=createSprite(l,"bib_"+u,0,0,k/3,v/2);C.x=x.x+10;C.y=r.y;C.scaleX=C.scaleY=.65;c.addChild(C);x=createBitmap(g);x.x=C.x+.65*k+10;x.y=r.y+2;c.addChild(x);r=new createjs.Text(s_oGameSettings.getForecastOdd(d,u),"18px "+PRIMARY_FONT,"#fff");r.textAlign="center";r.textBaseline="alphabetic";r.x=x.x+g.width/2;r.y=x.y+g.height/2+6;c.addChild(r);r=new CButBet(x.x+g.width+.72*m.width/2+5,x.y+.72*
m.height/2,m,.45,c);r.setScale(.72);r.addEventListenerWithParams(ON_MOUSE_UP,this._onForecastClicked,this,{first:d,second:u});a["forecast_"+d+"_"+u]=r;h+=.65*v+5}};this.setX=function(d){c.x=d};this._onForecastClicked=function(d){var p=CHIP_VALUES[s_oBetPanel.getChipSelected()];s_oBetPanel.setForecastBet(d.first,d.second,p,a["forecast_"+d.first+"_"+d.second])&&a["forecast_"+d.first+"_"+d.second].increaseBet(p)};var q=e;this._init(b,n)}
function CBetList(){var b,n,e;this._init=function(){this.reset()};this.reset=function(){b=[];for(var a=0;a<NUM_GREYHOUNDS;a++)b[a]=[],b[a].place_1=0,b[a].place_2=0,b[a].place_3=0;n=[];for(a=0;a<NUM_GREYHOUNDS;a++){n[a]=[];for(var c=0;c<NUM_GREYHOUNDS;c++)n[a][c]=0}e=[]};this.addSimpleBet=function(a,c,q){b[a]["place_"+c]+=q;var d=0;switch(c){case 1:d=q*s_oGameSettings.getOddWin(a);break;case 2:d=q*s_oGameSettings.getOddPlace(a);break;case 3:d=q*s_oGameSettings.getOddShow(a)}e.push({type_bet:"simple",
greyhounds:[{index:a,place:c}],bet:q,win:d})};this.addForecastBet=function(a,c,q){n[a][c]+=q;e.push({type_bet:"forecast",greyhounds:[{index:a,place:1},{index:c,place:2}],bet:q,win:q*s_oGameSettings.getForecastOdd(a,c)})};this.getMinWin=function(){if(0<e.length){for(var a=e[0].win,c=1;c<e.length;c++)a>e[c].win&&(a=e[c].win);return a}return 0};this.getTotWinWithCurRank=function(a){var c=0,q=[];if(0<b[a[0]].place_1){var d=b[a[0]].place_1*s_oGameSettings.getOddWin(a[0]);d=parseFloat(d.toFixed(2));c+=
d;q.push({win:d,greyhounds:a[0],bet:b[a[0]].place_1,type:"win"})}0<b[a[0]].place_2&&(d=b[a[0]].place_2*s_oGameSettings.getOddPlace(a[0]),d=parseFloat(d.toFixed(2)),c+=d,q.push({win:d,greyhounds:a[0],bet:b[a[0]].place_2,type:"place"}));0<b[a[1]].place_2&&(d=b[a[1]].place_2*s_oGameSettings.getOddPlace(a[1]),d=parseFloat(d.toFixed(2)),c+=d,q.push({win:d,greyhounds:a[1],bet:b[a[1]].place_2,type:"place"}));0<b[a[0]].place_3&&(d=b[a[0]].place_3*parseFloat(s_oGameSettings.getOddShow(a[0])),d=parseFloat(d.toFixed(2)),
c+=d,q.push({win:d,greyhounds:a[0],bet:b[a[0]].place_3,type:"show"}));0<b[a[1]].place_3&&(d=b[a[1]].place_3*s_oGameSettings.getOddShow(a[1]),d=parseFloat(d.toFixed(2)),c+=d,q.push({win:d,greyhounds:a[1],bet:b[a[1]].place_3,type:"show"}));0<b[a[2]].place_3&&(d=b[a[2]].place_3*s_oGameSettings.getOddShow(a[2]),d=parseFloat(d.toFixed(2)),c+=d,q.push({win:d,greyhounds:a[2],bet:b[a[2]].place_3,type:"show"}));0<n[a[0]][a[1]]&&(d=n[a[0]][a[1]]*s_oGameSettings.getForecastOdd(a[0],a[1]),d=parseFloat(d.toFixed(2)),
c+=d,q.push({win:d,greyhounds:[a[0],a[1]],bet:n[a[0]][a[1]],type:"forecast"}));return{tot_win:c,win_list:q}};s_oBetList=this;this._init()}var s_oBetList=null;
function CFichesController(b,n){var e,a,c,q,d,p,h,g,m,l,k,v;this._init=function(r){q=r;m=new createjs.Container;u.addChild(m);p=new CVector2;p.set(m.x,m.y);l=new createjs.Container;u.addChild(l);r*=18;v=new createjs.Text("",r+"px "+TERTIARY_FONT,"#000");v.textAlign="center";l.addChild(v);k=new createjs.Text("",r+"px "+TERTIARY_FONT,"#fff");k.textAlign="center";l.addChild(k);c=d=a=0;e=!1};this.addEventListener=function(r,x,C){};this.reset=function(){e=!1;c=0;m.removeAllChildren();m.x=p.getX();m.y=
p.getY();v.text="";k.text=""};this.setPrevValue=function(r){d=r};this.refreshFiches=function(r,x,C){r=r.sortOn("value","index");for(var f=x,w=C,y=c=0,z=0;z<r.length;z++)(new CFicheBut(r[z].index,f,w,b,m)).disable(),w-=5,y++,9<y&&(y=0,f+=FICHE_WIDTH,w=C),c+=r[z].value;playSound("chip",1,0);k.x=x;k.y=C+25*q;k.text=c.toFixed(2)+TEXT_CURRENCY;v.x=x+2;v.y=C+27*q;v.text=c.toFixed(2)+TEXT_CURRENCY};this.createFichesPile=function(r,x,C){this.reset();var f=CHIP_VALUES,w=[];do{for(var y=f[f.length-1],z=f.length-
1;y>r;)z--,y=f[z];z=Math.floor(r/y);for(var E=0;E<z;E++)w.push({value:y,index:s_oGameSettings.getIndexForFiches(y)});y=Math.floor(r/y)===r/y?0:r%y;r=y.toFixed(2)}while(0<y);this.refreshFiches(w,x,C*q)};this.initMovement=function(r,x){d=c;h=new CVector2(m.x,m.y);g=new CVector2(r,x);k.text="";v.text="";e=!0};this.getValue=function(){return c};this.getPrevBet=function(){return d};this.update=function(r){if(e)if(a+=r,a>TIME_FICHES_MOV)a=0,e=!1;else{r=easeInOutCubic(a,0,1,TIME_FICHES_MOV);var x=new CVector2;
x=tweenVectors(h,g,r,x);m.x=x.getX();m.y=x.getY()}};var u=n;this._init(b)}
function CButBet(b,n,e,a,c){var q,d,p,h,g,m,l,k,v,u=!1,r,x;this._init=function(w,y,z,E){q=0;d=[];p=[];g=[];x=new createjs.Container;x.x=w;x.y=y;C.addChild(x);h=createBitmap(z);l=m=1;h.regX=z.width/2;h.regY=z.height/2;s_bMobile||(h.cursor="pointer");x.addChild(h);this._initListener();r=new CFichesController(E,x)};this.unload=function(){h.off("mousedown",k);h.off("pressup",v);C.removeChild(x)};this.setVisible=function(w){h.visible=w};this.setCursorType=function(w){h.cursor=w};this._initListener=function(){k=
h.on("mousedown",this.buttonDown);v=h.on("pressup",this.buttonRelease)};this.addEventListener=function(w,y,z){d[w]=y;p[w]=z};this.addEventListenerWithParams=function(w,y,z,E){d[w]=y;p[w]=z;g[w]=E};this.buttonRelease=function(){u||(h.scaleX=0<m?m:-m,h.scaleY=l,playSound("chip",1,0),d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(p[ON_MOUSE_UP],g[ON_MOUSE_UP]))};this.buttonDown=function(){u||(h.scaleX=0<m?.9*m:.9*-m,h.scaleY=.9*l,d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN],g[ON_MOUSE_DOWN]))};this.rotation=
function(w){h.rotation=w};this.getButton=function(){return h};this.setPosition=function(w,y){h.x=w;h.y=y};this.setX=function(w){h.x=w};this.setY=function(w){h.y=w};this.getButtonImage=function(){return h};this.block=function(w){u=w;h.scaleX=m;h.scaleY=l};this.setScaleX=function(w){m=h.scaleX=w};this.setScale=function(w){l=m=w;h.scaleX=h.scaleY=w};this.increaseBet=function(w){q+=w;r.createFichesPile(q.toFixed(2),0,-4)};this.clearBet=function(){q=0;r.reset()};this.getX=function(){return h.x};this.getY=
function(){return h.y};this.pulseAnimation=function(){createjs.Tween.get(h).to({scaleX:.9*m,scaleY:.9*l},850,createjs.Ease.quadOut).to({scaleX:m,scaleY:l},650,createjs.Ease.quadIn).call(function(){f.pulseAnimation()})};this.trebleAnimation=function(){createjs.Tween.get(h).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){f.trebleAnimation()})};this.removeAllTweens=function(){createjs.Tween.removeTweens(h)};
this.getTotBet=function(){return q};var C=void 0!==c?c:s_oStage;this._init(b,n,e,a);var f=this;return this}
function CVector2(b,n){var e,a;this._init=function(c,q){e=c;a=q};this.add=function(c,q){e+=c;a+=q};this.addV=function(c){e+=c.getX();a+=c.getY()};this.scalarDivision=function(c){e/=c;a/=c};this.subV=function(c){e-=c.getX();a-=c.getY()};this.scalarProduct=function(c){e*=c;a*=c};this.invert=function(){e*=-1;a*=-1};this.dotProduct=function(c){return e*c.getX()+a*c.getY()};this.set=function(c,q){e=c;a=q};this.setV=function(c){e=c.getX();a=c.getY()};this.length=function(){return Math.sqrt(e*e+a*a)};this.length2=
function(){return e*e+a*a};this.normalize=function(){var c=this.length();0<c&&(e/=c,a/=c)};this.getNormalize=function(c){this.length();c.set(e,a);c.normalize()};this.rot90CCW=function(){var c=e;e=-a;a=c};this.rot90CW=function(){var c=e;e=a;a=-c};this.getRotCCW=function(c){c.set(e,a);c.rot90CCW()};this.getRotCW=function(c){c.set(e,a);c.rot90CW()};this.ceil=function(){e=Math.ceil(e);a=Math.ceil(a)};this.round=function(){e=Math.round(e);a=Math.round(a)};this.toString=function(){return"Vector2: "+e+", "+
a};this.print=function(){trace("Vector2: "+e+", "+a)};this.getX=function(){return e};this.getY=function(){return a};this._init(b,n)}
function CMsgBox(){var b,n,e,a,c;this._init=function(){e=new createjs.Container;e.alpha=0;e.visible=!1;s_oStage.addChild(e);b=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));e.addChild(b);n=new CTLText(e,CANVAS_WIDTH/2-200,CANVAS_HEIGHT/2-100,400,130,34,"center","#fff",PRIMARY_FONT,1,0,0," ",!0,!0,!0,!1);a=new CTextButton(CANVAS_WIDTH/2,460,s_oSpriteLibrary.getSprite("fiche_panel"),TEXT_RECHARGE,PRIMARY_FONT,"#fff",30,e);a.setVisible(!1);a.addEventListener(ON_MOUSE_UP,this._onRecharge,this);c=
new CGfxButton(CANVAS_WIDTH/2+205,CANVAS_HEIGHT/2-130,s_oSpriteLibrary.getSprite("but_exit"),e);c.addEventListener(ON_MOUSE_UP,this._onExit,this)};this.unload=function(){a.unload();c.unload()};this.show=function(q,d){n.refreshText(q);e.visible=!0;createjs.Tween.get(e).to({alpha:1},500);d?a.setVisible(!0):a.setVisible(!1)};this._onExit=function(){e.visible=!1};this._onRecharge=function(){$(s_oMain).trigger("recharge");e.visible=!1};this._init();return this}
function CTrackBg(b){var n,e,a,c,q,d;this._init=function(){d=new createjs.Container;p.addChild(d);e=0;a=2;c=0;q=[];for(var h=0;h<NUM_TRACK_BG;h++){var g=createBitmap(s_oSpriteLibrary.getSprite("bg_track_"+h));0<h&&(g.visible=!1);d.addChild(g);q[h]=g}n=!0};this.update=function(){if(!n)return e;c++;c===a&&(c=0,e++,q[e].visible=!0,q[e-1].visible=!1,e===q.length-1?(n=!1,s_oGame.checkGreyhoundArrival()):17===e&&s_oGame.startGreyhounds());return e};var p=b;this._init()}
function CGreyhound(b,n,e,a,c,q){var d,p,h,g,m,l,k,v,u,r,x;this._init=function(f,w,y,z,E){p=!1;h=w;k=0;v=ARRIVAL_X-GREYHOUND_WIDTH/2*z+30;u=y;r=E;w={framerate:40,images:[s_oSpriteLibrary.getSprite("greyhound_"+w)],frames:{width:GREYHOUND_WIDTH,height:GREYHOUND_HEIGHT,regX:GREYHOUND_WIDTH/2,regY:GREYHOUND_HEIGHT},animations:{idle:[0,0],anim:[0,21],start:[22],anim_1:[5,21,"anim"],anim_2:[10,21,"anim"],anim_3:[15,21,"anim"]}};w=new createjs.SpriteSheet(w);x=createSprite(w,"start",GREYHOUND_WIDTH/2,GREYHOUND_HEIGHT,
GREYHOUND_WIDTH,GREYHOUND_HEIGHT);x.x=f.x;x.y=f.y;x.scaleX=x.scaleY=z;x.alpha=0;C.addChild(x)};this.startRace=function(){var f="anim_"+(Math.floor(3*Math.random())+1);createjs.Tween.get(x).to({alpha:1},150).call(function(){x.gotoAndPlay(f)});l=x.x;g=0;m=r[k].frame;d=!0};this.pauseAnim=function(){x.paused=!0};this.unpauseAnim=function(){x.paused=!1};this.getX=function(){return x.x};this.update=function(f){if(d){g++;if(g>=m)k++,k<r.length?(g=0,m=r[k].frame,l=x.x):d=!1;else{var w=s_oTweenController.easeLinear(g,
0,1,m);w=s_oTweenController.tweenValue(l,r[k].x,w);x.x=w}f&&!p&&x.x>=v&&(p=!0,s_oGame.greyhoundPhotofinish(h-1,u))}};var C=q;this._init(b,n,e,a,c)}
function CTweenController(){this.tweenValue=function(b,n,e){return b+e*(n-b)};this.easeLinear=function(b,n,e,a){return e*b/a+n};this.easeInCubic=function(b,n,e,a){a=(b/=a)*b*b;return n+e*a};this.easeBackInQuart=function(b,n,e,a){a=(b/=a)*b;return n+e*(2*a*a+2*a*b+-3*a)};this.easeInBack=function(b,n,e,a){return e*(b/=a)*b*(2.70158*b-1.70158)+n};this.easeOutCubic=function(b,n,e,a){return e*((b=b/a-1)*b*b+1)+n};this.getTrajectoryPoint=function(b,n){var e=new createjs.Point,a=(1-b)*(1-b),c=b*b;e.x=a*
n.start.x+2*(1-b)*b*n.traj.x+c*n.end.x;e.y=a*n.start.y+2*(1-b)*b*n.traj.y+c*n.end.y;return e}}
function CRankingGui(b,n){var e,a,c,q,d,p,h;this._init=function(m){var l=s_oSpriteLibrary.getSprite("rank_panel");e=CANVAS_HEIGHT-l.height+6;h=new createjs.Container;h.x=0;h.y=e;g.addChild(h);l=createBitmap(l);h.addChild(l);q=[];q[0]=new createjs.Point(780,48);q[1]=new createjs.Point(642,48);q[2]=new createjs.Point(504,48);q[3]=new createjs.Point(366,48);q[4]=new createjs.Point(228,48);q[5]=new createjs.Point(90,48);this._initBibs(m);a=2;d=createBitmap(s_oSpriteLibrary.getSprite("fill_bar"));d.x=
107;d.y=116;h.addChild(d);p=new createjs.Shape;p.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y-2,.01,10);h.addChild(p);d.mask=p;this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(m,l){h.y=e-l};this._initBibs=function(m){c=[];for(var l=0;l<NUM_GREYHOUNDS;l++){var k=new createjs.Container;k.x=q[l].x;k.y=q[l].y;h.addChild(k);var v=createBitmap(s_oSpriteLibrary.getSprite("bib_gui_"+l));k.addChild(v);new CTLText(k,-28,0,80,12,12,"right","#fff",PRIMARY_FONT,1,0,
0,m[l].toUpperCase(),!0,!0,!1,!1);c.push(k)}};this.refreshRank=function(m){for(var l=0;l<m.length;l++)createjs.Tween.get(c[m[l].index]).to({x:q[l].x},1E3,createjs.Ease.cubicOut)};this.refreshRadar=function(m){p.graphics.clear();p.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y-2,a*m,10)};var g=n;this._init(b)}
function CArrivalPanel(b,n,e){var a,c,q,d,p,h,g;this._init=function(l,k){d=0;c=l;q=k;g=new createjs.Container;g.x=c;g.y=q;m.addChild(g);var v=s_oSpriteLibrary.getSprite("panel_arrival");v=createBitmap(v);g.addChild(v);v=s_oSpriteLibrary.getSprite("bibs");var u=v.width/3,r=v.height/2,x=new createjs.SpriteSheet({images:[v],frames:{width:u,height:r},animations:{bib_0:[0],bib_1:[1],bib_2:[2],bib_3:[3],bib_4:[4],bib_5:[5]}});p=[];h=[];for(var C=6,f=0;f<NUM_GREYHOUNDS;f++){var w=createSprite(x,"bib_0",
0,0,u,r);w.x=10;w.y=C;w.visible=!1;w.scaleX=w.scaleY=.5;g.addChild(w);h.push(w);w=new CTLText(g,w.x+.5*u+5,w.y+12,120,15,15,"left","#fff",TERTIARY_FONT,1,0,0," ",!0,!0,!1,!1);p.push(w);C+=.5*r+4}a=CANVAS_WIDTH-v.width};this.show=function(){createjs.Tween.get(g).to({x:a},500,createjs.Ease.cubicOut)};this.hide=function(){createjs.Tween.get(g).to({x:c},500,createjs.Ease.cubicOut)};this.refreshRank=function(l,k){p[d].refreshText(k);h[d].gotoAndStop("bib_"+l);h[d].visible=!0;0===d&&this.show();d++};var m=
e;this._init(b,n)}
function CWinPanel(b){var n,e,a,c,q,d;this._init=function(){d=new createjs.Container;d.visible=!1;p.addChild(d);var h=createBitmap(s_oSpriteLibrary.getSprite("win_panel"));d.addChild(h);h=s_oSpriteLibrary.getSprite("bibs");n=h.width/3;e=h.height/2;a=new createjs.SpriteSheet({images:[h],frames:{width:n,height:e},animations:{bib_0:[0],bib_1:[1],bib_2:[2],bib_3:[3],bib_4:[4],bib_5:[5]}});q=new CTLText(d,CANVAS_WIDTH/2+15,450,120,80,30,"center","#ffde00",SECONDARY_FONT,1,0,0,TEXT_WIN,!0,!0,!0,!1);c=new CGfxButton(700,
491,s_oSpriteLibrary.getSprite("but_skip"),d);c.addEventListener(ON_MOUSE_UP,this.onSkip,this)};this.unload=function(){c.unload()};this.show=function(h,g,m){q.refreshText(TEXT_WIN+"\n"+h+TEXT_CURRENCY);h=310;for(var l=0;3>l;l++){var k={images:[s_oSpriteLibrary.getSprite("greyhound_"+(m[l]+1))],frames:{width:GREYHOUND_WIDTH,height:GREYHOUND_HEIGHT,regX:GREYHOUND_WIDTH/2,regY:GREYHOUND_HEIGHT},animations:{idle:[18,18],anim:[0,21],start:[22],anim_1:[5,21,"anim"],anim_2:[10,21,"anim"],anim_3:[15,21,"anim"]}};
k=new createjs.SpriteSheet(k);k=createSprite(k,"idle",GREYHOUND_WIDTH/2,GREYHOUND_HEIGHT,GREYHOUND_WIDTH,GREYHOUND_HEIGHT);k.scaleX=k.scaleY=.5;k.x=CANVAS_WIDTH/2+150;k.y=h;d.addChild(k);h+=68}h=CANVAS_HEIGHT/2-150;for(m=0;m<g.length;m++){if("forecast"===g[m].type){k=g[m].greyhounds;var v=createSprite(a,"bib_"+k[0],0,0,n,e);v.x=280;v.y=h;v.scaleX=v.scaleY=.5;d.addChild(v);l=new createjs.Text("X","20px "+PRIMARY_FONT,"#fff");l.textAlign="center";l.textBaseline="middle";l.x=v.x+.5*n+10;l.y=h+15;d.addChild(l);
k=createSprite(a,"bib_"+k[1],0,0,n,e);k.x=l.x+10;k.y=h;k.scaleX=k.scaleY=.5;d.addChild(k);k=k.x+35}else v=createSprite(a,"bib_"+g[m].greyhounds,0,0,n,e),v.x=280,v.y=h,v.scaleX=v.scaleY=.5,d.addChild(v),k=v.x+35;l=new createjs.Text(g[m].type.toUpperCase(),"16px "+PRIMARY_FONT,"#ffb400");l.textAlign="left";l.textBaseline="alphabetic";l.x=k;l.y=h+22;d.addChild(l);k=new createjs.Text(TEXT_WIN+": "+g[m].win+TEXT_CURRENCY,"16px "+PRIMARY_FONT,"#fff");k.textAlign="left";k.textBaseline="alphabetic";k.x=l.x+
l.getBounds().width+10;k.y=h+22;d.addChild(k);h+=35}d.visible=!0;d.alpha=0;createjs.Tween.get(d).wait(1E3).to({alpha:1},500,createjs.Ease.cubicOut)};this.onSkip=function(){s_oGame.returnInBetPanel()};var p=b;this._init()}
function CLosePanel(b){var n,e,a,c,q,d;this._init=function(){d=new createjs.Container;d.visible=!1;p.addChild(d);var h=createBitmap(s_oSpriteLibrary.getSprite("lose_panel"));d.addChild(h);new CTLText(d,CANVAS_WIDTH/2-200,250,400,50,50,"center","#fff",PRIMARY_FONT,1,0,0,TEXT_NO_WIN,!0,!0,!0,!1);h=s_oSpriteLibrary.getSprite("bibs");n=h.width/3;e=h.height/2;c=new createjs.SpriteSheet({images:[h],frames:{width:n,height:e},animations:{bib_0:[0],bib_1:[1],bib_2:[2],bib_3:[3],bib_4:[4],bib_5:[5]}});a=[];
h=createSprite(c,"bib_0",0,0,n,e);h.x=CANVAS_WIDTH/2-100-n/2;h.y=350;d.addChild(h);a.push(h);h=createSprite(c,"bib_0",0,0,n,e);h.x=CANVAS_WIDTH/2-n/2;h.y=350;d.addChild(h);a.push(h);h=createSprite(c,"bib_0",0,0,n,e);h.x=CANVAS_WIDTH/2+100-n/2;h.y=350;d.addChild(h);a.push(h);new CTLText(d,CANVAS_WIDTH/2-200,500,400,30,30,"center","#fff",PRIMARY_FONT,1,0,0,TEXT_WIN+": 0.00 "+TEXT_CURRENCY,!0,!0,!0,!1);q=new CGfxButton(700,480,s_oSpriteLibrary.getSprite("but_skip"),d);q.addEventListener(ON_MOUSE_UP,
this.onSkip,this)};this.unload=function(){q.unload()};this.show=function(h){for(var g=0;3>g;g++)a[g].gotoAndStop("bib_"+h[g]);d.visible=!0;d.alpha=0;createjs.Tween.get(d).wait(1E3).to({alpha:1},500,createjs.Ease.cubicOut)};this.onSkip=function(){s_oGame.returnInBetPanel()};var p=b;this._init()}
function CButStartRace(b,n,e,a,c,q,d){var p,h,g,m,l,k;this._init=function(u,r,x,C,f,w){p=[];h=[];g=new createjs.Container;g.x=u;g.y=r;g.regX=x.width/2;g.regY=x.height/2;v.addChild(g);u=createBitmap(x);g.addChild(u);m=new CTLText(g,0,6,x.width,w,w,"center",f,PRIMARY_FONT,1,0,0,C,!0,!0,!0,!1);s_bMobile||(g.cursor="pointer");this._initListener()};this.unload=function(){g.off("mousedown",l);g.off("pressup",k);v.removeChild(g)};this.setVisible=function(u){g.visible=u};this._initListener=function(){l=g.on("mousedown",
this.buttonDown);k=g.on("pressup",this.buttonRelease)};this.addEventListener=function(u,r,x){p[u]=r;h[u]=x};this.buttonRelease=function(){g.scaleX=1;g.scaleY=1;playSound("click",1,0);p[ON_MOUSE_UP]&&p[ON_MOUSE_UP].call(h[ON_MOUSE_UP])};this.buttonDown=function(){g.scaleX=.9;g.scaleY=.9;p[ON_MOUSE_DOWN]&&p[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};this.setTextPosition=function(u){m.setY(u)};this.setPosition=function(u,r){g.x=u;g.y=r};this.setX=function(u){g.x=u};this.setY=function(u){g.y=u};this.getButtonImage=
function(){return g};this.getX=function(){return g.x};this.getY=function(){return g.y};var v=d;this._init(b,n,e,a,c,q);return this}
function CAreYouSurePanel(b){var n,e,a,c;this._init=function(){c=new createjs.Container;c.visible=!1;n=c.on("click",function(){});q.addChild(c);var d=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));c.addChild(d);new CTLText(c,CANVAS_WIDTH/2-200,250,400,100,50,"center","#fff",PRIMARY_FONT,1,0,0,TEXT_ARE_YOU_SURE,!0,!0,!0,!1);e=new CGfxButton(CANVAS_WIDTH/2+170,460,s_oSpriteLibrary.getSprite("but_yes"),c);e.addEventListener(ON_MOUSE_UP,this._onReleaseYes,this);a=new CGfxButton(CANVAS_WIDTH/2-170,
460,s_oSpriteLibrary.getSprite("but_no"),c);a.addEventListener(ON_MOUSE_UP,this._onReleaseNo,this)};this.unload=function(){c.off("click",n);a.unload();e.unload()};this.show=function(){c.visible=!0;c.alpha=0;createjs.Tween.get(c).to({alpha:1},500,createjs.Ease.cubicOut)};this._onReleaseYes=function(){s_oGame.onExit()};this._onReleaseNo=function(){c.visible=!1;s_oGame.unpause()};var q=b;this._init(b)}
CTLText.prototype={constructor:CTLText,__autofit:function(){if(this._bFitText){for(var b=this._iFontSize;(this._oText.getBounds().height>this._iHeight-2*this._iPaddingV||this._oText.getBounds().width>this._iWidth-2*this._iPaddingH)&&!(b--,this._oText.font=b+"px "+this._szFont,this._oText.lineHeight=Math.round(b*this._fLineHeightFactor),this.__updateY(),this.__verticalAlign(),8>b););this._iFontSize=b}},__verticalAlign:function(){if(this._bVerticalAlign){var b=this._oText.getBounds().height;this._oText.y-=
(b-this._iHeight)/2+this._iPaddingV}},__updateY:function(){this._oText.y=this._y+this._iPaddingV;switch(this._oText.textBaseline){case "middle":this._oText.y+=this._oText.lineHeight/2+(this._iFontSize*this._fLineHeightFactor-this._iFontSize)}},__createText:function(b){this._bDebug&&(this._oDebugShape=new createjs.Shape,this._oDebugShape.graphics.beginFill("rgba(255,0,0,0.5)").drawRect(this._x,this._y,this._iWidth,this._iHeight),this._oContainer.addChild(this._oDebugShape));this._oText=new createjs.Text(b,
this._iFontSize+"px "+this._szFont,this._szColor);this._oText.textBaseline="middle";this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this._oText.textAlign=this._szAlign;this._oText.lineWidth=this._bMultiline?this._iWidth-2*this._iPaddingH:null;switch(this._szAlign){case "center":this._oText.x=this._x+this._iWidth/2;break;case "left":this._oText.x=this._x+this._iPaddingH;break;case "right":this._oText.x=this._x+this._iWidth-this._iPaddingH}this._oContainer.addChild(this._oText);
this.refreshText(b)},setVerticalAlign:function(b){this._bVerticalAlign=b},setOutline:function(b){null!==this._oText&&(this._oText.outline=b)},setVisible:function(b){this._oContainer.visible=b},setShadow:function(b,n,e,a){null!==this._oText&&(this._oText.shadow=new createjs.Shadow(b,n,e,a))},setColor:function(b){this._oText.color=b},setAlpha:function(b){this._oText.alpha=b},setY:function(b){this._oText.y=b},removeTweens:function(){createjs.Tween.removeTweens(this._oText)},getText:function(){return this._oText},
getY:function(){return this._y},getFontSize:function(){return this._iFontSize},refreshText:function(b){""===b&&(b=" ");null===this._oText&&this.__createText(b);this._oText.text=b;this._oText.font=this._iFontSize+"px "+this._szFont;this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this.__autofit();this.__updateY();this.__verticalAlign()}};
function CTLText(b,n,e,a,c,q,d,p,h,g,m,l,k,v,u,r,x){this._oContainer=b;this._x=n;this._y=e;this._iWidth=a;this._iHeight=c;this._bMultiline=r;this._iFontSize=q;this._szAlign=d;this._szColor=p;this._szFont=h;this._iPaddingH=m;this._iPaddingV=l;this._bVerticalAlign=u;this._bFitText=v;this._bDebug=x;this._oDebugShape=null;this._fLineHeightFactor=g;this._oText=null;k&&this.__createText(k)}
function CFicheBut(b,n,e,a,c){var q,d,p,h=[],g,m;this._init=function(l,k){var v=s_oSpriteLibrary.getSprite("fiche_"+b);q=!1;m=new createjs.Container;m.x=l;m.y=k;m.regX=v.width/2;m.regY=v.height/2;c.addChild(m);d=[];p=[];g=createBitmap(v);g.cursor="pointer";m.addChild(g);m.scaleX=m.scaleY=a;new CTLText(m,11,11,18,18,20,"center",COLOR_FICHES[b],PRIMARY_FONT,1.1,0,0,CHIP_VALUES[b],!0,!0,!1,!1);this._initListener()};this.unload=function(){m.off("mousedown",this.buttonDown);m.off("pressup",this.buttonRelease);
c.removeChild(m)};this.select=function(){};this.deselect=function(){};this.enable=function(){q=!1};this.disable=function(){q=!0};this.setVisible=function(l){m.visible=l};this._initListener=function(){m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};this.addEventListener=function(l,k,v){d[l]=k;p[l]=v};this.addEventListenerWithParams=function(l,k,v,u){d[l]=k;p[l]=v;h=u};this.buttonRelease=function(){q||(playSound("click",1,!1),m.scaleX=a,m.scaleY=a,d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(p[ON_MOUSE_UP],
h))};this.buttonDown=function(){q||(m.scaleX=.9*a,m.scaleY=.9*a,d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN],h))};this.setPosition=function(l,k){m.x=l;m.y=k};this.setX=function(l){m.x=l};this.setY=function(l){m.y=l};this.getX=function(){return m.x};this.getY=function(){return m.y};this._init(n,e)};